resources:
  repositories:
    - repository: Template
      type: git
      name: SAP CI CD/Azure DevOps Pipeline Templates

parameters:
- name: TransportID
  displayName: Transport Request via SAP Cloud Transport Management (cTMS) (Relevant only for QA/PROD deployments)
  type: number
  default: 0
- name: Environment 
  displayName: Environment
  default: DEV
  values:
  - DEV
  - QA
  - PROD

trigger:
- main

extends:
  template: BTP-Template-Prod.yml@Template
  parameters:
    TRANSPORT_ID: ${{ parameters.TransportID }}
    ENV: ${{ parameters.Environment }}

appendCommitMessageToRunName: false