resources:
  repositories:
    - repository: Template
      type: git
      name: SAP CI CD/Azure DevOps Pipeline Templates

parameters:
- name: TransportID
  displayName: Transport Request (Trigger via SAP Cloud Transport Management)
  type: number
  default: 0
- name: Environnement 
  displayName: QA or PRD
  default: QA
  values:
  - QA
  - PRD
- name: SNChange 
  displayName: Enter your ServiceNow Change Request (Only PRD)
  type: string
  default: CHGxxxxxx

trigger:
- main

extends:
  template: BTP-Template-Prod.yml@Template
  parameters:
    TRANSPORT_ID: ${{ parameters.TransportID }}
    ENV: ${{ parameters.Environnement }}
    CHANGE: ${{ parameters.SNChange }}
