Build:     
  ## mtaBuild
  verbose: false

  Release:     
    ## cloudFoundryDeploy
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    mtaDeployParameters: '-f --version-rule ALL'
    # mtaDeployParameters: '-f --delete-services --version-rule ALL'
    cfOrg: 'cf-order-management-dev-j4s5jpqjls'
    cfSpace: 'OM_Cockpit'
    apiProvider: 'https://api.cf.eu10-004.hana.ondemand.com/'

    ## tmsUpload
    nodeName: 'ORDER_MANAGEMENT_DEV_OM_Cockpit_OM_C'
    #nodeName: 'webplatform_DEV_MTA_CHARM'
    nodeExtDescriptorMapping:      
      #ORDER_QA_OM_Cockpit_CHARM: 'mtaext_qa.mtaext'
      #ORDER_PROD_OM_Cockpit_CHARM: 'mtaext_prod.mtaext'
      ORDER_MANAGEMENT_QA_OM_Cockpit_OM_C: 'mtaext_qa.mtaext'
      ORDER_MANAGEMENT_PROD_OM_Cockpit_OM: 'mtaext_prod.mtaext'