###
GET https://port5000-workspaces-ws-89dx8.eu10.applicationstudio.cloud.sap/odata/v4/open-orders-srv/callChatbotService(payload='')
cookie: dtCookie=v_4_srv_1_sn_765786ECDB81BAEBDD3D055B12D1429F_perc_100000_ol_0_mul_1_app-3Acab67a9e1543df82_0; workspaces-ws-85hp9_WSR_SESSIONID=IZ/k0NHhtVT0CXRJ9LkXYLDhUM8rs6ye1nnEBzPynRyMWLX89cl3/ZGGzY9bVC3xDxUxyUIpBOWLbM54zKjStg==; workspaces-ws-89dx8_WSR_SESSIONID=CvpbFeuilcJoyzXFe7b9uEt0YTuBWPEJ+OwAsL7wOdsifl/yqt8zLYGBcRPnNwuGiGqh5cOLD/N6icCcyePQ4w==; workspaces-ws-pfb8p_WSR_SESSIONID=/iY/SvMRgb/mVOsRSIl4qD3pBwyoge39oTf8lPLrdP3lmNnEsBr6NmApjIFzOywqgIdKN2jX0WtUBVViYLvsaQ==; JSESSIONID=s%3A31C2OM5jnLrNgJF2t4f_f8PQ-e7cO5df.A0EynN8RO8gZD%2FAeiFeZSGR%2FIOxbp5saJhjwEbGmUa8