using order_monitoring_services as db from './external/order-monitoring-services.csn';
using allorders.db as db_app from  '../db/order-monitoring-app-service';

service srvOpenOrders {
  @readonly
  @cds.redirection.target: true
  entity Results as
    select from db.Results {
      key null as id : UUID,
          MANDT,
          SO_VBELN,
          SO_POSNR,
          SO_ERDAT_ORDER,
          SO_ERDAT_ITEM,
          SO_AUART,
          SO_WERKS,
          SO_VTWEG,
          SO_MATNR,
          SO_MAKTX,
          SO_KDMAT,
          SO_BSTNK,
          SO_AG_PARTNER,
          SO_WE_PARTNER,
          SO_LAND1,
          SO_LANDX,
          SO_ORT01,
          SO_VKORG,
          SO_VKORG_NAME1,
          SO_KNREF_HEAD,
          SO_KNREF_ITM,
          SO_VBUND,
          SO_EDATU_REQUESTED,
          SO_KWMENG,
          SO_VRKME,
          SO_EDATU_CONFIRMED,
          SO_KBMENG,
          SO_LDDAT,
          SO_UNCONFIRMED_QTY,
          SO_REQ_TEXT,
          SO_FAKSP,
          SO_FAKSP_VTEXT,
          SO_LGORT,
          SO_SUPPLY_SITUATION,
          SO_SUPPLY_SITUATION_DESCR,
          SO_KBETR,
          SO_WAERS,
          SO_KPEIN,
          SO_KMEIN,
          SO_NETWR,
          SO_WAERK,
          SO_HTEXT,
          SO_PSTYV,
          SO_PSTYV_VTEXT,
          SO_DISPO,
          SO_KOSCH,
          SO_VKBUR,
          SO_VKBUR_BEZEI,
          SO_ABGRU,
          SO_ABSTA,
          SO_KNUMV,
          SO_SPART,
          SO_CO_PARTNER,
          SO_CO_PARTNER_NAME,
          SO_NY_PARTNER,
          SO_NY_PARTNER_NAME,
          SO_AS_PARTNER,
          SO_AS_PARTNER_NAME,
          SO_VE_PARTNER,
          SO_VE_PARTNER_NAME,
          SO_AM_PARTNER,
          SO_AM_PARTNER_NAME,
          SO_AG_PARTNER_NAME,
          SO_WE_PARTNER_NAME,
          SO_INCO1,
          SO_INCO2,
          SO_zterm,
          SO_PRSDT,
          SO_ZZ0S2REVG2,
          SO_ZZDKPPRODB,
          SO_BSARK,
          SO_BSARK_VTEXT,
          DL_VBELN,
          DL_POSNR,
          DL_CHARG,
          DL_LFIMG,
          DL_VRKME,
          DL_POSAR,
          DL_VGBEL,
          DL_VGPOS,
          DL_LFART,
          DL_LFART_VTEXT,
          DL_LFDAT,
          DL_HSDAT,
          DL_VFDAT,
          DL_TRAID,
          DL_ZZ0S2BLNR,
          DL_PEND_DEL_QUAN,
          LAST_NOTE,
          USERNAME,
          // LANGUAGE,
          TM_TKNUM,
          TM_VSART,
          TM_VSART_BEZEI,
          TM_EXTI1,
          TM_TDLNR,
          TM_TDLNR_NAME1,
          TM_TRACKING_ID_COMP,
          TM_TRACKING_ID_ELEM,
          TM_DPTBG,
          TM_DATBG,
          TM_DPTEN,
          TM_DATEN
          // TM_AR_DATE,
          // TM_STTRG,
          // TM_STTRG_DDTEXT,
          // TM_SHIPMENT_ALERT,
          // TM_SHIPMENT_CURRENT_STATUS,
          // SO_BASF_LOFCR,
          // SO_GUSCON_LEVEL,
          // SO_I_VBELN,
          // SO_ISCOMPLETED,
          // SO_LEVEL_TYPE,
          // SO_N_VBELN,
          // SO_F_VBELN,
          // SO_F_POSNR,
          // SO_VBTYP,
          // SO_BSTKD,
          // BL_VBELN_INV_FIRST,
          // BL_VBELN_INV_LAST,
          // BL_XBLNR,
          // SO_TRAGR,
          // SO_TRAGR_VTEXT,
          // SO_VKGRP,
          // SO_VKGRP_BEZEI,
          // SO_ROUTE,
          // SO_TDDAT,
          // SO_ZZ0S2MATUG,
          // SO_VSBED,
          // SO_VSBED_VTEXT,
          // SO_F_WERKS,
          // SO_F_VKORG,
          // SO_F_VKORG_VTEXT,
          // DL_WADAT,
          // DL_WADAT_IST
    };
entity valueHelps as
    select from db.Results {
  key null as id : UUID,
          MANDT,
          SO_VBELN,
          SO_POSNR,
          SO_ERDAT_ORDER,
          SO_ERDAT_ITEM,
          SO_AUART,
          SO_WERKS,
          SO_VTWEG,
          SO_MATNR,
          SO_MAKTX,
          SO_KDMAT,
          SO_BSTNK,
          SO_AG_PARTNER,
          SO_WE_PARTNER,
          SO_LAND1,
          SO_LANDX,
          SO_ORT01,
          SO_VKORG,
          SO_VKORG_NAME1,
          SO_KNREF_HEAD,
          SO_KNREF_ITM,
          SO_VBUND,
          SO_EDATU_REQUESTED,
          SO_KWMENG,
          SO_VRKME,
          SO_EDATU_CONFIRMED,
          SO_KBMENG,
          SO_LDDAT,
          SO_UNCONFIRMED_QTY,
          SO_REQ_TEXT,
          SO_FAKSP,
          SO_FAKSP_VTEXT,
          SO_LGORT,
          SO_SUPPLY_SITUATION,
          SO_SUPPLY_SITUATION_DESCR,
          SO_KBETR,
          SO_WAERS,
          SO_KPEIN,
          SO_KMEIN,
          SO_NETWR,
          SO_WAERK,
          SO_HTEXT,
          SO_PSTYV,
          SO_PSTYV_VTEXT,
          SO_DISPO,
          SO_KOSCH,
          SO_VKBUR,
          SO_VKBUR_BEZEI,
          SO_ABGRU,
          SO_ABSTA,
          SO_KNUMV,
          SO_SPART,
          SO_CO_PARTNER,
          SO_CO_PARTNER_NAME,
          SO_NY_PARTNER,
          SO_NY_PARTNER_NAME,
          SO_AS_PARTNER,
          SO_AS_PARTNER_NAME,
          SO_VE_PARTNER,
          SO_VE_PARTNER_NAME,
          SO_AM_PARTNER,
          SO_AM_PARTNER_NAME,
          SO_AG_PARTNER_NAME,
          SO_WE_PARTNER_NAME,
          SO_INCO1,
          SO_INCO2,
          SO_zterm,
          SO_PRSDT,
          SO_ZZ0S2REVG2,
          SO_ZZDKPPRODB,
          SO_BSARK,
          SO_BSARK_VTEXT,
          DL_VBELN,
          DL_POSNR,
          DL_CHARG,
          DL_LFIMG,
          DL_VRKME,
          DL_POSAR,
          DL_VGBEL,
          DL_VGPOS,
          DL_LFART,
          DL_LFART_VTEXT,
          DL_LFDAT,
          DL_HSDAT,
          DL_VFDAT,
          DL_TRAID,
          DL_ZZ0S2BLNR,
          DL_PEND_DEL_QUAN,
          LAST_NOTE,
          USRENAME,
          // LANGUAGE,
          TM_TKNUM,
          TM_VSART,
          TM_VSART_BEZEI,
          TM_EXTI1,
          TM_TDLNR,
          TM_TDLNR_NAME1,
          TM_TRACKING_ID_COMP,
          TM_TRACKING_ID_ELEM,
          TM_DPTBG,
          TM_DATBG,
          TM_DPTEN,
          TM_DATEN
          // TM_AR_DATE,
          // TM_STTRG,
          // TM_STTRG_DDTEXT,
          // TM_SHIPMENT_ALERT,
          // TM_SHIPMENT_CURRENT_STATUS,
          // SO_BASF_LOFCR,
          // SO_GUSCON_LEVEL,
          // SO_I_VBELN,
          // SO_ISCOMPLETED,
          // SO_LEVEL_TYPE,
          // SO_N_VBELN,
          // SO_F_VBELN,
          // SO_F_POSNR,
          // SO_VBTYP,
          // SO_BSTKD,
          // BL_VBELN_INV_FIRST,
          // BL_VBELN_INV_LAST,
          // BL_XBLNR,
          // SO_TRAGR,
          // SO_TRAGR_VTEXT,
          // SO_VKGRP,
          // SO_VKGRP_BEZEI,
          // SO_ROUTE,
          // SO_TDDAT,
          // SO_ZZ0S2MATUG,
          // SO_VSBED,
          // SO_VSBED_VTEXT,
          // SO_F_WERKS,
          // SO_F_VKORG,
          // SO_F_VKORG_VTEXT,
          // DL_WADAT,
          // DL_WADAT_IST
  };

   entity notes           as
    select from db.notes {
      // key CLIENT,
      // key ID,
      // key VBELN,
      // key POSNR,
      //     *
      key UTCTIME,
          CLIENT,
          VBELN,
          POSNR,
          LANGUAGE,
          NOTE_TITLE,
          NOTE_TEXT,
          USERNAME
    };

  entity PartnerSettings as
    select from db_app.PARTNER_SETTINGS {
      key CLIENT,
      key BASF_USER,
      key PARTNER_ROLE,
      key PARTNER_NUMBER,
          *
    };
}
