using order_monitoring_services as db from './external/order-monitoring-services.csn';
using allorders.db as db_app from '../db/order-monitoring-app-service';

service srvOpenOrders {
  @readonly
  @cds.redirection.target: true
  entity BaseEntity         as
    select from db_app.RESULTS {
      key null as id : UUID,
          SO_MANDT as SO_MANDT,
          SO_VBELN,
          SO_POSNR,
          SO_ERDAT_ORDER,
          SO_ERDAT_ITEM,
          SO_AUART,
          SO_WERKS,
          SO_VTWEG,
          SO_MATNR,
          SO_MAKTX,
          SO_KDMAT,
          SO_AG_PARTNER,
          SO_AG_PARTNER_NAME1 || ' ' || SO_AG_PARTNER_NAME2 as SO_AG_PARTNER_NAME : String(70),
          SO_WE_PARTNER,
          SO_WE_PARTNER_NAME1 || ' ' || SO_WE_PARTNER_NAME2 as SO_WE_PARTNER_NAME : String(70),
          IFNULL(SO_CO_PARTNER_ITM, SO_CO_PARTNER_HEAD) AS SO_CO_PARTNER : String(10),
          IFNULL((SO_CO_PARTNER_NAME1_HEAD || SO_CO_PARTNER_NAME2_HEAD), (SO_CO_PARTNER_NAME1_ITM || SO_CO_PARTNER_NAME2_ITM)) AS SO_CO_PARTNER_NAME : String(70),
          IFNULL(SO_NY_PARTNER_ITM, SO_NY_PARTNER_HEAD) AS SO_NY_PARTNER : String(10),
          IFNULL((SO_NY_PARTNER_NAME1_HEAD || SO_NY_PARTNER_NAME2_HEAD), (SO_NY_PARTNER_NAME1_ITM || SO_NY_PARTNER_NAME2_ITM)) AS SO_NY_PARTNER_NAME : String(70),
          IFNULL(SO_AS_PARTNER_ITM, SO_AS_PARTNER_HEAD) AS SO_AS_PARTNER : String(8),
          IFNULL(SO_AS_PARTNER_NAME_ITM, SO_AS_PARTNER_NAME_HEAD) AS SO_AS_PARTNER_NAME : String(40),
          IFNULL(SO_VE_PARTNER_ITM, SO_VE_PARTNER_HEAD) AS SO_VE_PARTNER : String(8),
          IFNULL(SO_VE_PARTNER_NAME_ITM, SO_VE_PARTNER_NAME_HEAD) AS SO_VE_PARTNER_NAME : String(40),
          IFNULL(SO_AM_PARTNER_ITM, SO_AM_PARTNER_HEAD) AS SO_AM_PARTNER : String(8),
          IFNULL(SO_AM_PARTNER_NAME_ITM, SO_AM_PARTNER_NAME_HEAD) AS SO_AM_PARTNER_NAME : String(40),
          SO_LAND1,
          SO_LANDX,
          SO_ORT01,
          SO_VKORG,
          SO_VKORG_NAME1,
          SO_KNREF_HEAD,
          SO_KNREF_ITM,
          SO_VBUND,
          SO_EDATU_REQUESTED,
          SO_KWMENG,
          SO_VRKME,
          SO_EDATU_CONFIRMED,
          SO_KBMENG,
          SO_LDDAT,
          SO_UNCONFIRMED_QTY,
          SO_REQ_TEXT,
          SO_FAKSP,
          SO_FAKSP_VTEXT,
          SO_LGORT,
          SO_SUPPLY_SITUATION,
          SO_SUPPLY_SITUATION_DESCR,
          IFNULL(SO_KBETR, SO_KBETR_ALT) AS SO_KBETR : Decimal(11, 2),
          IFNULL(SO_WAERS, SO_WAERS_ALT) AS SO_WAERS : String(5),
          IFNULL(SO_KPEIN, SO_KPEIN_ALT) AS SO_KPEIN : Decimal(5),
          IFNULL(SO_KMEIN, SO_KMEIN_ALT) AS SO_KMEIN : String(3),
          SO_NETWR,
          SO_WAERK,
          SO_HTEXT,
          SO_PSTYV,
          SO_PSTYV_VTEXT,
          SO_DISPO,
          SO_KOSCH,
          SO_VKBUR,
          SO_VKBUR_BEZEI,
          SO_ABGRU,
          SO_ABSTA,
          SO_KNUMV,
          SO_SPART,
          IFNULL(SO_INCO1_ITEM, SO_INCO1_HEAD) AS SO_INCO1 : String(3),
          IFNULL(SO_INCO2_ITEM, SO_INCO2_HEAD) AS SO_INCO2 : String(28),
          IFNULL(SO_ZTERM_ITEM, SO_ZTERM_HEAD) AS SO_ZTERM : String(4),
          SO_PRSDT,
          SO_ZZ0S2REVG2,
          SO_ZZDKPPRODB,
          SO_BSARK,
          SO_BSARK_VTEXT,
          SO_BASF_LOFCR,
          // SO_GUSCON,
          // SO_GUSCON_ITM,
          SO_GUSCON_LEVEL,
          SO_I_VBELN,
          // SO_I_POSNR,
          SO_ISCOMPLETED,
          SO_LEVEL_TYPE,
          SO_N_VBELN,
          // SO_N_POSNR,
          SO_F_VBELN,
          SO_F_POSNR,
          SO_VBTYP,
          SO_BSTKD,
          SO_TRAGR,
          SO_TRAGR_VTEXT,
          SO_VKGRP,
          SO_VKGRP_BEZEI,
          SO_ROUTE,
          // SO_AUFNR,
          // SO_DGLTP,
          // SO_PSMNG,
          // SO_AMEIN,
          SO_F_WERKS,
          SO_F_VKORG,
          SO_F_VKORG_VTEXT,
          SO_F_TDDAT,
          SO_F_ZZ0S2MATUG,
          SO_F_VSBED,
          SO_F_VSBED_VTEXT,
          DL_VBELN,
          DL_POSNR,
          DL_CHARG,
          DL_LFIMG,
          DL_VRKME,
          DL_POSAR,
          DL_VGBEL,
          DL_VGPOS,
          DL_LFART,
          DL_LFART_VTEXT,
          DL_LFDAT,
          DL_HSDAT,
          DL_VFDAT,
          DL_TRAID,
          DL_ZZ0S2BLNR,
          DL_PEND_DEL_QUAN,
          DL_WADAT,
          DL_WADAT_IST,
          LAST_NOTE,
          
          TM_TKNUM,
          TM_VSART,
          TM_VSART_BEZEI,
          TM_EXTI1,
          TM_TDLNR,
          TM_TDLNR_NAME1,

          case when ( TM_STATUS_REASON_CODE_TEXT_ELEM is null or TM_STATUS_REASON_CODE_TEXT_ELEM = '' )
            then  TM_STATUS_CODE_TEXT_ELEM
            else  TM_STATUS_CODE_TEXT_ELEM || ' (' || TM_STATUS_REASON_CODE_ELEM || ' - ' || TM_STATUS_REASON_CODE_TEXT_ELEM || ')'
            end as TM_SHIPMENT_CURRENT_STATUS_ELEM : String(250),

          case when ( TM_REASON_CODE_TEXT_COMP is null or TM_REASON_CODE_TEXT_COMP = '') 
            then TM_STATUS_CODE_TEXT_COMP 
            else TM_STATUS_CODE_TEXT_COMP || ' (' || TM_REASON_CODE_COMP || ' - ' || TM_REASON_CODE_TEXT_COMP || ')'   
            end as TM_SHIPMENT_CURRENT_STATUS_COMP : String(250),

          case when ( TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM IS NULL OR TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM = '' )
            then TM_ALERT_STATUS_CODE_TEXT_ELEM
            else TM_ALERT_STATUS_CODE_TEXT_ELEM || '(' || TM_ALERT_STATUS_REASON_CODE_ELEM || ' - ' || TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM || ')' 
          end as TM_SHIPMENT_ALERT : String(250),  

          // TM_STATUS_CODE_ELEM,
          // TM_STATUS_REASON_CODE_ELEM,
          // TM_STATUS_CODE_TEXT_ELEM,
          // TM_STATUS_REASON_CODE_TEXT_ELEM,
          TM_TRACKING_ID_ELEM,
          // TM_ALERT_STATUS_CODE_ELEM,
          // TM_ALERT_STATUS_REASON_CODE_ELEM,
          // TM_ALERT_STATUS_CODE_TEXT_ELEM,
          // TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM,
          // TM_STATUS_CODE_COMP,
          // TM_REASON_CODE_COMP,
          // TM_STATUS_CODE_TEXT_COMP,
          // TM_REASON_CODE_TEXT_COMP,
          TM_TRACKING_ID_COMP,
          // TM_STATUS_CODE_MANUEL,
          TM_DPTBG,
          TM_DATBG,
          TM_DPTEN,
          TM_DATEN,
          TM_AR_DATE,
          TM_STTRG,
          TM_STTRG_DDTEXT,
          BL_VBELN_INV_FIRST,
          BL_VBELN_INV_LAST,
          BL_XBLNR
    };

    entity Results as projection on BaseEntity {
      *,
      IFNULL(TM_SHIPMENT_CURRENT_STATUS_ELEM, TM_SHIPMENT_CURRENT_STATUS_COMP) as TM_SHIPMENT_CURRENT_STATUS : String(250)
    };

    entity valueHelps as projection on BaseEntity {
      *,
      IFNULL(TM_SHIPMENT_CURRENT_STATUS_ELEM, TM_SHIPMENT_CURRENT_STATUS_COMP) as TM_SHIPMENT_CURRENT_STATUS : String(250)
    };


  entity baseValueHelps      as
    select from db_app.RESULTS {
      key null as id : UUID,
          SO_MANDT as SO_MANDT,
          SO_VBELN,
          SO_POSNR,
          SO_ERDAT_ORDER,
          SO_ERDAT_ITEM,
          SO_AUART,
          SO_WERKS,
          SO_VTWEG,
          SO_MATNR,
          SO_MAKTX,
          SO_KDMAT,
          SO_AG_PARTNER,
          SO_AG_PARTNER_NAME1 || ' ' || SO_AG_PARTNER_NAME2 as SO_AG_PARTNER_NAME : String(70),
          SO_WE_PARTNER,
          SO_WE_PARTNER_NAME1 || ' ' || SO_WE_PARTNER_NAME2 as SO_WE_PARTNER_NAME : String(70),
          IFNULL(SO_CO_PARTNER_ITM, SO_CO_PARTNER_HEAD) AS SO_CO_PARTNER : String(10),
          IFNULL((SO_CO_PARTNER_NAME1_HEAD || SO_CO_PARTNER_NAME2_HEAD), (SO_CO_PARTNER_NAME1_ITM || SO_CO_PARTNER_NAME2_ITM)) AS SO_CO_PARTNER_NAME : String(70),
          IFNULL(SO_NY_PARTNER_ITM, SO_NY_PARTNER_HEAD) AS SO_NY_PARTNER : String(10),
          IFNULL((SO_NY_PARTNER_NAME1_HEAD || SO_NY_PARTNER_NAME2_HEAD), (SO_NY_PARTNER_NAME1_ITM || SO_NY_PARTNER_NAME2_ITM)) AS SO_NY_PARTNER_NAME : String(70),
          IFNULL(SO_AS_PARTNER_ITM, SO_AS_PARTNER_HEAD) AS SO_AS_PARTNER : String(8),
          IFNULL(SO_AS_PARTNER_NAME_ITM, SO_AS_PARTNER_NAME_HEAD) AS SO_AS_PARTNER_NAME : String(40),
          IFNULL(SO_VE_PARTNER_ITM, SO_VE_PARTNER_HEAD) AS SO_VE_PARTNER : String(8),
          IFNULL(SO_VE_PARTNER_NAME_ITM, SO_VE_PARTNER_NAME_HEAD) AS SO_VE_PARTNER_NAME : String(40),
          IFNULL(SO_AM_PARTNER_ITM, SO_AM_PARTNER_HEAD) AS SO_AM_PARTNER : String(8),
          IFNULL(SO_AM_PARTNER_NAME_ITM, SO_AM_PARTNER_NAME_HEAD) AS SO_AM_PARTNER_NAME : String(40),
          SO_LAND1,
          SO_LANDX,
          SO_ORT01,
          SO_VKORG,
          SO_VKORG_NAME1,
          SO_KNREF_HEAD,
          SO_KNREF_ITM,
          SO_VBUND,
          SO_EDATU_REQUESTED,
          SO_KWMENG,
          SO_VRKME,
          SO_EDATU_CONFIRMED,
          SO_KBMENG,
          SO_LDDAT,
          SO_UNCONFIRMED_QTY,
          SO_REQ_TEXT,
          SO_FAKSP,
          SO_FAKSP_VTEXT,
          SO_LGORT,
          SO_SUPPLY_SITUATION,
          SO_SUPPLY_SITUATION_DESCR,
          IFNULL(SO_KBETR, SO_KBETR_ALT) AS SO_KBETR : Decimal(11, 2),
          IFNULL(SO_WAERS, SO_WAERS_ALT) AS SO_WAERS : String(5),
          IFNULL(SO_KPEIN, SO_KPEIN_ALT) AS SO_KPEIN : Decimal(5),
          IFNULL(SO_KMEIN, SO_KMEIN_ALT) AS SO_KMEIN : String(3),
          SO_NETWR,
          SO_WAERK,
          SO_HTEXT,
          SO_PSTYV,
          SO_PSTYV_VTEXT,
          SO_DISPO,
          SO_KOSCH,
          SO_VKBUR,
          SO_VKBUR_BEZEI,
          SO_ABGRU,
          SO_ABSTA,
          SO_KNUMV,
          SO_SPART,
          IFNULL(SO_INCO1_ITEM, SO_INCO1_HEAD) AS SO_INCO1 : String(3),
          IFNULL(SO_INCO2_ITEM, SO_INCO2_HEAD) AS SO_INCO2 : String(28),
          IFNULL(SO_ZTERM_ITEM, SO_ZTERM_HEAD) AS SO_ZTERM : String(4),
          SO_PRSDT,
          SO_ZZ0S2REVG2,
          SO_ZZDKPPRODB,
          SO_BSARK,
          SO_BSARK_VTEXT,
          SO_BASF_LOFCR,
          // SO_GUSCON,
          // SO_GUSCON_ITM,
          SO_GUSCON_LEVEL,
          SO_I_VBELN,
          // SO_I_POSNR,
          SO_ISCOMPLETED,
          SO_LEVEL_TYPE,
          SO_N_VBELN,
          // SO_N_POSNR,
          SO_F_VBELN,
          SO_F_POSNR,
          SO_VBTYP,
          SO_BSTKD,
          SO_TRAGR,
          SO_TRAGR_VTEXT,
          SO_VKGRP,
          SO_VKGRP_BEZEI,
          SO_ROUTE,
          // SO_AUFNR,
          // SO_DGLTP,
          // SO_PSMNG,
          // SO_AMEIN,
          SO_F_WERKS,
          SO_F_VKORG,
          SO_F_VKORG_VTEXT,
          SO_F_TDDAT,
          SO_F_ZZ0S2MATUG,
          SO_F_VSBED,
          SO_F_VSBED_VTEXT,
          DL_VBELN,
          DL_POSNR,
          DL_CHARG,
          DL_LFIMG,
          DL_VRKME,
          DL_POSAR,
          DL_VGBEL,
          DL_VGPOS,
          DL_LFART,
          DL_LFART_VTEXT,
          DL_LFDAT,
          DL_HSDAT,
          DL_VFDAT,
          DL_TRAID,
          DL_ZZ0S2BLNR,
          DL_PEND_DEL_QUAN,
          DL_WADAT,
          DL_WADAT_IST,
          LAST_NOTE,
          TM_TKNUM,
          TM_VSART,
          TM_VSART_BEZEI,
          TM_EXTI1,
          TM_TDLNR,
          TM_TDLNR_NAME1,
          // TM_STATUS_CODE_ELEM,
          // TM_STATUS_REASON_CODE_ELEM,
          // TM_STATUS_CODE_TEXT_ELEM,
          // TM_STATUS_REASON_CODE_TEXT_ELEM,
          TM_TRACKING_ID_ELEM,
          // TM_ALERT_STATUS_CODE_ELEM,
          // TM_ALERT_STATUS_REASON_CODE_ELEM,
          // TM_ALERT_STATUS_CODE_TEXT_ELEM,
          // TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM,
          // TM_STATUS_CODE_COMP,
          // TM_REASON_CODE_COMP,
          // TM_STATUS_CODE_TEXT_COMP,
          // TM_REASON_CODE_TEXT_COMP,
          TM_TRACKING_ID_COMP,
          // TM_STATUS_CODE_MANUEL,
          TM_DPTBG,
          TM_DATBG,
          TM_DPTEN,
          TM_DATEN,
          TM_AR_DATE,
          TM_STTRG,
          TM_STTRG_DDTEXT,
          BL_VBELN_INV_FIRST,
          BL_VBELN_INV_LAST,
          BL_XBLNR
    };

  entity notes           as
    select from db.notes {
      key UTCTIME,
          CLIENT,
          VBELN,
          POSNR,
          LANGUAGE,
          NOTE_TITLE,
          NOTE_TEXT,
          USERNAME
    };

  entity PartnerSettings as
    select from db_app.PARTNER_SETTINGS {
      key CLIENT,
      key BASF_USER,
      key PARTNER_ROLE,
      key PARTNER_NUMBER,
          *
    };
}
