namespace openorders.db;

using {User} from '@sap/cds/common';

@cds.persistence.exists
entity ![OPENORDERSLIST] {
        MANDT                              : String(3);
        VBELN                              : String(10);
        POSNR                              : String(6);
        ERDAT_ORDER                        : String(8);
        ERDAT_ORDER_DATE                   : Date = ERDAT_ORDER;
        ERDAT_ITEM                         : String(8);
        ERDAT_ITEM_DATE                    : Date = ERDAT_ORDER;
        AUART                              : String(4);
        WERKS                              : String(4);
        VTWEG                              : String(2);
        MATNR                              : String(18);
        KDMAT                              : String(35);
        BSTNK                              : String(20);
        AG_PARTNER                         : String(10);
        AG_PARTNER_NAME1                   : String(35);
        AG_PARTNER_NAME2                   : String(35);
        WE_PARTNER                         : String(10);
        WE_PARTNER_NAME1                   : String(35);
        WE_PARTNER_NAME2                   : String(35);
        LAND1                              : String(3);
        ORT01                              : String(35);
        VKORG                              : String(4);
        VKORG_NAME1                        : String(40);
        CO_PARTNER_HEAD                    : String(10);
        CO_PARTNER_NAME1_HEAD              : String(35);
        CO_PARTNER_NAME2_HEAD              : String(35);
        CO_PARTNER_ITM                     : String(10);
        CO_PARTNER_NAME1_ITM               : String(35);
        CO_PARTNER_NAME2_ITM               : String(35);
        NY_PARTNER_HEAD                    : String(10);
        NY_PARTNER_NAME1_HEAD              : String(35);
        NY_PARTNER_NAME2_HEAD              : String(35);
        NY_PARTNER_ITM                     : String(10);
        NY_PARTNER_NAME1_ITM               : String(35);
        NY_PARTNER_NAME2_ITM               : String(35);
        AS_PARTNER_HEAD                    : String(8);
        AS_PARTNER_NAME_HEAD               : String(40);
        AS_PARTNER_ITM                     : String(8);
        AS_PARTNER_NAME_ITM                : String(40);
        VE_PARTNER_HEAD                    : String(8);
        VE_PARTNER_NAME_HEAD               : String(40);
        VE_PARTNER_ITM                     : String(8);
        VE_PARTNER_NAME_ITM                : String(40);
        AM_PARTNER_HEAD                    : String(8);
        AM_PARTNER_NAME_HEAD               : String(40);
        AM_PARTNER_ITM                     : String(8);
        AM_PARTNER_NAME_ITM                : String(40);
        KNREF_HEAD                         : String(30);
        KNREF_ITM                          : String(30);
        VBUND                              : String(6);
        EDATU_REQUESTED                    : String(8);
        EDATU_REQUESTED_DATE               : Date = EDATU_REQUESTED;
        KWMENG                             : Decimal(15);
        VRKME                              : String(3);
        EDATU_CONFIRMED                    : String(8);
        EDATU_CONFIRMED_DATE               : Date = EDATU_CONFIRMED;
        KBMENG                             : Decimal(15);
        UNCONFIRMED_QTY                    : Decimal(15);
        REQ_TEXT                           : String(250);
        FAKSP                              : String(2);
        SUPPLY_SITUATION                   : Int16;
        SUPPLY_SITUATION_DESCR             : String(60);
        KBETR                              : Decimal(11);
        WAERS                              : String(5);
        KPEIN                              : Decimal(5);
        KMEIN                              : String(3);
        KBETR_ALT                          : Decimal(11);
        WAERS_ALT                          : String(5);
        KPEIN_ALT                          : Decimal(5);
        KMEIN_ALT                          : String(3);
        NETWR                              : Decimal(15);
        WAERK                              : String(5);
        HTEXT                              : String(4000);
        PSTYV                              : String(4);
        DISPO                              : String(3);
        KOSCH                              : String(18);
        VKBUR                              : String(4);
        ABGRU                              : String(2);
        ABSTA                              : String(1);
        KNUMV                              : String(10);
        SPART                              : String(2);
        INCO1_ITEM                         : String(3);
        INCO2_ITEM                         : String(28);
        ZTERM_ITEM                         : String(4);
        INCO1_HEAD                         : String(3);
        INCO2_HEAD                         : String(28);
        ZTERM_HEAD                         : String(4);
        PRSDT                              : String(8);
        PRSDT_DATE                         : Date = PRSDT;
        ZZ0S2REVG2                         : String(10);
        ZZDKPPRODB                         : String(18);
        BSARK                              : String(4);
        _BASF_LOFCR                        : String(20);
        GUSCON_LEVEL                       : String(2);
        FIRST_SO                           : String(10);
        FIRST_POSNR                        : String(6);
        LEVEL_TYPE                         : String(7);
        NEXT_SO                            : String(10);
        NEXT_POSNR                         : String(6);
        FINAL_SO                           : String(10);
        FINAL_POSNR                        : String(6);
        VBTYP                              : String(1);
        BSTKD                              : String(35);
        TRAGR                              : String(4);
        VKGRP                              : String(3);
        ROUTE                              : String(6);
        FAKSK                              : String(2);
        MAKTX_LANG                         : String(40);
        LANDX_LANG                         : String(15);
        FAKSP_VTEXT_LANG                   : String(20);
        PSTYV_VTEXT_LANG                   : String(20);
        VKBUR_BEZEI_LANG                   : String(20);
        BSARK_VTEXT_LANG                   : String(20);
        TRAGR_VTEXT_LANG                   : String(20);
        VKGRP_BEZEI_LANG                   : String(20);
        FAKSK_VTEXT_LANG                   : String(20);
        ABGRU_BEZEI_LANG                   : String(20);
        F_WERKS                            : String(4);
        F_VKORG                            : String(4);
        F_VKORG_NAME1                      : String(40);
        F_AS_PARTNER_HEAD                  : String(8);
        F_AS_PARTNER_NAME_HEAD             : String(40);
        F_AS_PARTNER_ITM                   : String(8);
        F_AS_PARTNER_NAME_ITM              : String(40);
        F_LDDAT                            : String(8);
        F_LDDAT_DATE                       : Date = F_LDDAT;
        F_LGORT                            : String(4);
        F_TDDAT                            : String(8);
        F_TDDAT_DATE                       : Date = F_TDDAT;
        F_ZZ0S2MATUG                       : String(18);
        F_AUFNR                            : String(12);
        F_DGLTP                            : String(8);
        F_DGLTP_DATE                       : Date = F_DGLTP;
        F_AMEIN                            : String(3);
        F_PSMNG                            : Decimal(13);
        F_VSBED                            : String(2);
        F_VSBED_VTEXT_LANG                 : String(20);
        F_MANDT                            : String(3);
        F_VBELN                            : String(10);
        F_POSNR                            : String(6);
        MANDT_DEL                          : String(3);
        VBELN_DEL                          : String(10);
        POSNR_DEL                          : String(6);
        CHARG                              : String(10);
        HSDAT                              : String(8);
        HSDAT_DATE                         : Date = HSDAT;
        VFDAT                              : String(8);
        VFDAT_DATE                         : Date = VFDAT;
        LFIMG                              : Decimal(13);
        VRKME_1                            : String(3);
        POSAR                              : String(1);
        VGBEL                              : String(10);
        VGPOS                              : String(6);
        LFART                              : String(4);
        LFART_VTEXT_LANG                   : String(20);
        LFDAT                              : String(8);
        LFDAT_DATE                         : Date = LFDAT;
        TRAID                              : String(20);
        ZZ0S2BLNR                          : String(30);
        PEND_DEL_QUAN                      : String(500);
        WADAT                              : String(8);
        WADAT_DATE                         : Date = WADAT;
        WADAT_IST                          : String(8);
        WADAT_IST_DATE                     : Date = WADAT_IST;
        MANDT_TM                           : String(3);
        TKNUM                              : String(10);
        VSART                              : String(2);
        EXTI1                              : String(20);
        DPTBG                              : String(8);
        DPTBG_DATE                         : Date = DPTBG;
        DATBG                              : String(8);
        DATBG_DATE                         : Date = DATBG;
        DPTEN                              : String(8);
        DPTEN_DATE                         : Date = DPTEN;
        DATEN                              : String(8);
        DATEN_DATE                         : Date = DATEN;
        AR_DATE                            : String(8);
        AR_DATE_DATE                       : Date = AR_DATE;
        TDLNR                              : String(10);
        TDLNR_NAME1                        : String(35);
        STATUS_CODE_ELEM                   : String(3);
        STATUS_REASON_CODE_ELEM            : String(3);
        STATUS_CODE_TEXT_ELEM              : String(255);
        STATUS_REASON_CODE_TEXT_ELEM       : String(255);
        TRACKING_ID_ELEM                   : String(12);
        ALERT_STATUS_CODE_ELEM             : String(3);
        ALERT_STATUS_REASON_CODE_ELEM      : String(3);
        ALERT_STATUS_CODE_TEXT_ELEM        : String(255);
        ALERT_STATUS_REASON_CODE_TEXT_ELEM : String(255);
        STATUS_CODE_COMP                   : String(3);
        REASON_CODE_COMP                   : String(17);
        STATUS_CODE_TEXT_COMP              : String(100);
        REASON_CODE_TEXT_COMP              : String(100);
        TRACKING_ID_COMP                   : String(50);
        STATUS_CODE_MANUEL                 : String(3);
        STTRG                              : String(1);
        VSART_BEZEI_LANG                   : String(20);
        STTRG_DDTEXT_LANG                  : String(60);
        NPS                                : String(2);
        ISSUE                              : String(2);
        DUE_DATE                           : String(8);
        DUE_DATE_FORMATTED                 : Date = DUE_DATE;
        ISSUE_LOCATION                     : String(12);
        ISSUE_LOCATION_ITEM                : String(6);
        NOTE_TEXT                          : String(1000);
        IGNORED                            : Integer;
        ETA_UPDATED                        : String(3);
        BL_VBELN_INV_FIRST                 : String(10);
        BL_POSNR_INV_FIRST                 : String(6);
        BL_VBELN_INV_LAST                  : String(10);
        BL_POSNR_INV_LAST                  : String(6);
        XBLNR                              : String(16);
        BL_MANDT_INV_FIRST                 : String(3);
        BL_MANDT_INV_LAST                  : String(3);
        BL_FKIMG_FIRST                     : Decimal(15,3);
        BL_FKIMG_LAST                      : Decimal(15,3);
        BL_VRKME_FIRST                     : String(3);
        BL_VRKME_LAST                      : String(3);
        BL_FKART_FIRST                     : String(4);
        BL_FKART_LAST                      : String(4);
        DOCUMENT_TYPE                      : String(1);
        FOLLOWUP_NOTES_LANG                : String(50);
        REASON_CODE_01_LANG                : String(255);
        REASON_CODE_02_LANG                : String(255);
        REASON_CODE_03_LANG                : String(255);
        REASON_CODE_04_LANG                : String(255);
        REASON_CODE_05_LANG                : String(255);
        DEV_CONF_DATE                      : String(12);
        EMAIL                              : String(241);
        EMAIL_SEND_DATE_F                  : String(8);
        EMAIL_SENT_ON                      : String(8);
        MDB                                : String(3);
        MDB_TEXT                           : String(60);
        // DCP_ITEM_STATUS                    : String(2);
        ERDAT_DEL                          : String(8);	
        ERDAT_DEL_DATE                     : Date = ERDAT_DEL;	
        LDDAT_DEL                          : String(8);	
        LDDAT_DEL_DATE                     : Date = LDDAT_DEL;	
}

entity ContactsOptions {
        key OptionKey  : String(10);
            OptionText : String;
            VBELN      : String(10);
            POSNR      : String(6);
            MANDT      : String(3);
}

entity ![DUE_DATE_LIMIT] {
        key userId   : User;
            dayLimit : Integer;
}

// entity ![UNRESTRICTED_USER] {
//         key userId : User;
// }

entity orderChangeUsers {
        key userId : User;
            active : Boolean;
}

@cds.persistence.exists
@cds.persistence.calcview
entity ![SALESORDER_DETAILS](IP_LANG : String(2)) {
        key MANDT                  : String(3);
        key VBELN                  : String(10);
        key POSNR                  : String(6);
            ERDAT_ORDER            : String(8);
            ERDAT_ITEM             : String(8);
            AUART                  : String(4);
            WERKS                  : String(4);
            VTWEG                  : String(2);
            MATNR                  : String(18);
            MAKTX_LANG             : String(40);
            KDMAT                  : String(35);
            AG_PARTNER             : String(10);
            AG_PARTNER_NAME1       : String(35);
            AG_PARTNER_NAME2       : String(35);
            WE_PARTNER             : String(10);
            WE_PARTNER_NAME1       : String(35);
            WE_PARTNER_NAME2       : String(35);
            CO_PARTNER_HEAD        : String(10);
            CO_PARTNER_NAME1_HEAD  : String(35);
            CO_PARTNER_NAME2_HEAD  : String(35);
            CO_PARTNER_ITM         : String(10);
            CO_PARTNER_NAME1_ITM   : String(35);
            CO_PARTNER_NAME2_ITM   : String(35);
            NY_PARTNER_HEAD        : String(10);
            NY_PARTNER_NAME1_HEAD  : String(35);
            NY_PARTNER_NAME2_HEAD  : String(35);
            NY_PARTNER_ITM         : String(10);
            NY_PARTNER_NAME1_ITM   : String(35);
            NY_PARTNER_NAME2_ITM   : String(35);
            AS_PARTNER_HEAD        : String(8);
            AS_PARTNER_NAME_HEAD   : String(40);
            AS_PARTNER_ITM         : String(8);
            AS_PARTNER_NAME_ITM    : String(40);
            VE_PARTNER_HEAD        : String(8);
            VE_PARTNER_NAME_HEAD   : String(40);
            VE_PARTNER_ITM         : String(8);
            VE_PARTNER_NAME_ITM    : String(40);
            AM_PARTNER_HEAD        : String(8);
            AM_PARTNER_NAME_HEAD   : String(40);
            AM_PARTNER_ITM         : String(8);
            AM_PARTNER_NAME_ITM    : String(40);
            LAND1                  : String(3);
            LANDX_LANG             : String(15);
            ORT01                  : String(35);
            VKORG                  : String(4);
            VKORG_NAME1            : String(40);
            KNREF_HEAD             : String(30);
            KNREF_ITM              : String(30);
            VBUND                  : String(6);
            EDATU_REQUESTED        : String(8);
            KWMENG                 : Decimal(15, 3);
            VRKME                  : String(3);
            EDATU_CONFIRMED        : String(8);
            KBMENG                 : Decimal(15, 3);
            LDDAT                  : String(8);
            UNCONFIRMED_QTY        : Decimal(15, 3);
            REQ_TEXT               : String(250);
            FAKSP                  : String(2);
            FAKSP_VTEXT_LANG       : String(20);
            LGORT                  : String(4);
            SUPPLY_SITUATION       : Int16;
            SUPPLY_SITUATION_DESCR : String(60);
            KBETR                  : Decimal(11, 2);
            KBETR_ALT              : Decimal(11, 2);
            WAERS                  : String(5);
            WAERS_ALT              : String(5);
            KPEIN                  : Decimal(5);
            KPEIN_ALT              : String(5);
            KMEIN                  : String(3);
            KMEIN_ALT              : String(3);
            NETWR                  : Decimal(15, 2);
            WAERK                  : String(5);
            HTEXT                  : String(4000);
            PSTYV                  : String(4);
            PSTYV_VTEXT_LANG       : String(20);
            DISPO                  : String(3);
            KOSCH                  : String(18);
            VKBUR                  : String(4);
            VKBUR_BEZEI_LANG       : String(20);
            ABGRU                  : String(2);
            ABSTA                  : String(1);
            KNUMV                  : String(10);
            SPART                  : String(2);
            INCO1_HEAD             : String(3);
            INCO1_ITEM             : String(3);
            INCO2_HEAD             : String(3);
            INCO2_ITEM             : String(28);
            ZTERM_HEAD             : String(4);
            ZTERM_ITEM             : String(4);
            PRSDT                  : String(8);
            ZZ0S2REVG2             : String(10);
            ZZDKPPRODB             : String(18);
            BSARK                  : String(4);
            BSARK_VTEXT_LANG       : String(20);
            BASF_LOFCR             : String(20);
            GUSCON                 : String(15);
            GUSCON_ITM             : String(6);
            GUSCON_LEVEL           : String(2);
            FIRST_SO               : String(10);
            FIRST_POSNR            : String(6);
            ISCOMPLETED            : String(1);
            LEVEL_TYPE             : String(1);
            NEXT_SO                : String(10);
            NEXT_POSNR             : String(6);
            FINAL_SO               : String(10);
            FINAL_POSNR            : String(6);
            VBTYP                  : String(1);
            BSTKD                  : String(35);
            TRAGR                  : String(4);
            TRAGR_VTEXT_LANG       : String(20);
            VKGRP                  : String(3);
            VKGRP_BEZEI_LANG       : String(20);
            ROUTE                  : String(6);
            TDDAT                  : String(8);
            ZZ0S2MATUG             : String(18);
            VSBED                  : String(2);
            VSBED_VTEXT_LANG       : String(20);
            AUFNR                  : String(12);
            DGLTP                  : String(8);
            AMEIN                  : String(3);
            PSMNG                  : Decimal(13, 3);
            FAKSK                  : String(2);
            FAKSK_VTEXT_LANG       : String(20);
            SO_LAST_UPDATE         : Timestamp;
}

@cds.persistence.exists
entity ![IGNORED_SO] {
        key MANDT    : String(3);
        key USERNAME : String(50);
        key VBELN    : String(10);
        key POSNR    : String(6);
        key NPS      : String(3);
            VALID_TO : String(8);
            COMMENT  : String(255);
            IGNORED  : Boolean
};

type issue_reason {
        text : String(255)
}
