namespace allorders.db;

@cds.persistence.exists
entity ![RESULTS] {

        MANDT                              : String(3);
        VBELN                              : String(10);
        POSNR                              : String(6);
        ERDAT_ORDER                        : String(8);
        SO_ERDAT_ORDER_DATE                : Date = ERDAT_ORDER;
        ERDAT_ITEM                         : String(8);
        SO_ERDAT_ITEM_DATE                 : Date = ERDAT_ITEM;
        AUART                              : String(4);
        WERKS                              : String(4);
        VTWEG                              : String(2);
        MATNR                              : String(18);
        MAKTX_LANG                         : String(40);
        KDMAT                              : String(35);
        AG_PARTNER                         : String(10);
        AG_PARTNER_NAME1                   : String(35);
        AG_PARTNER_NAME2                   : String(35);
        WE_PARTNER                         : String(10);
        WE_PARTNER_NAME1                   : String(35);
        WE_PARTNER_NAME2                   : String(35);
        CO_PARTNER_HEAD                    : String(10);
        CO_PARTNER_NAME1_HEAD              : String(35);
        CO_PARTNER_NAME2_HEAD              : String(35);
        CO_PARTNER_ITM                     : String(10);
        CO_PARTNER_NAME1_ITM               : String(35);
        CO_PARTNER_NAME2_ITM               : String(35);
        NY_PARTNER_HEAD                    : String(10);
        NY_PARTNER_NAME1_HEAD              : String(35);
        NY_PARTNER_NAME2_HEAD              : String(35);
        NY_PARTNER_ITM                     : String(10);
        NY_PARTNER_NAME1_ITM               : String(35);
        NY_PARTNER_NAME2_ITM               : String(35);
        AS_PARTNER_HEAD                    : String(8);
        AS_PARTNER_NAME_HEAD               : String(40);
        AS_PARTNER_ITM                     : String(8);
        AS_PARTNER_NAME_ITM                : String(40);
        VE_PARTNER_HEAD                    : String(8);
        VE_PARTNER_NAME_HEAD               : String(40);
        VE_PARTNER_ITM                     : String(8);
        VE_PARTNER_NAME_ITM                : String(40);
        AM_PARTNER_HEAD                    : String(8);
        AM_PARTNER_NAME_HEAD               : String(40);
        AM_PARTNER_ITM                     : String(8);
        AM_PARTNER_NAME_ITM                : String(40);
        LAND1                              : String(3);
        LANDX_LANG                         : String(15);
        ORT01                              : String(35);
        VKORG                              : String(4);
        VKORG_NAME1                        : String(40);
        KNREF_HEAD                         : String(30);
        KNREF_ITM                          : String(30);
        VBUND                              : String(6);
        EDATU_REQUESTED                    : String(8);
        SO_EDATU_REQUESTED_DATE            : Date = EDATU_REQUESTED;
        KWMENG                             : Decimal(15, 3);
        VRKME                              : String(3);
        EDATU_CONFIRMED                    : String(8);
        SO_EDATU_CONFIRMED_DATE            : Date = EDATU_CONFIRMED;
        KBMENG                             : Decimal(15, 3);
        UNCONFIRMED_QTY                    : Decimal(15, 3);
        REQ_TEXT                           : String(250);
        FAKSP                              : String(2);
        FAKSP_VTEXT_LANG                   : String(20);
        F_LGORT                            : String(4);
        SUPPLY_SITUATION                   : Int16;
        SUPPLY_SITUATION_DESCR             : String(60);
        KBETR                              : Decimal(11, 2);
        KBETR_ALT                          : Decimal(11, 2);
        WAERS                              : String(5);
        WAERS_ALT                          : String(5);
        KPEIN                              : Decimal(5);
        KPEIN_ALT                          : Decimal(5);
        KMEIN                              : String(3);
        KMEIN_ALT                          : String(3);
        NETWR                              : Decimal(15, 2);
        WAERK                              : String(5);
        HTEXT                              : String(4000);
        PSTYV                              : String(4);
        PSTYV_VTEXT_LANG                   : String(20);
        DISPO                              : String(3);
        KOSCH                              : String(18);
        VKBUR                              : String(4);
        VKBUR_BEZEI_LANG                   : String(20);
        ABGRU                              : String(2);
        ABSTA                              : String(1);
        KNUMV                              : String(10);
        SPART                              : String(2);
        INCO1_HEAD                         : String(3);
        INCO1_ITEM                         : String(3);
        INCO2_HEAD                         : String(28);
        INCO2_ITEM                         : String(28);
        ZTERM_HEAD                         : String(4);
        ZTERM_ITEM                         : String(4);
        PRSDT                              : String(8);
        SO_PRSDT_DATE                      : Date = PRSDT;
        ZZ0S2REVG2                         : String(10);
        ZZDKPPRODB                         : String(18);
        BSARK                              : String(4);
        BSARK_VTEXT_LANG                   : String(20);
        _BASF_LOFCR                        : String(20);
        GUSCON                             : String(15);
        GUSCON_ITM                         : String(6);
        GUSCON_LEVEL                       : String(2);
        FIRST_SO                           : String(10);
        FIRST_POSNR                        : String(6);
        ISCOMPLETED                        : String(1);
        LEVEL_TYPE                         : String(1);
        NEXT_SO                            : String(10);
        NEXT_POSNR                         : String(6);
        FINAL_SO                           : String(10);
        FINAL_POSNR                        : String(6);
        VBTYP                              : String(1);
        BSTKD                              : String(35);
        TRAGR                              : String(4);
        TRAGR_VTEXT_LANG                   : String(20);
        VKGRP                              : String(3);
        VKGRP_BEZEI_LANG                   : String(20);
        ROUTE                              : String(6);
        FAKSK                              : String(2);
        FAKSK_VTEXT_LANG                   : String(20);
        F_WERKS                            : String(4);
        F_VKORG                            : String(4);
        F_VKORG_NAME1                      : String(40);
        F_TDDAT                            : String(8);
        SO_F_TDDAT_DATE                    : Date = F_TDDAT;
        F_ZZ0S2MATUG                       : String(18);
        F_VSBED                            : String(2);
        F_VSBED_VTEXT_LANG                 : String(20);
        F_AUFNR                            : String(12);
        F_DGLTP                            : String(8);
        SO_F_DGLTP_DATE                    : Date = F_DGLTP;
        F_PSMNG                            : Decimal(13, 3);
        F_AMEIN                            : String(3);
        F_LDDAT                            : String(8);
        SO_F_LDDAT_DATE                    : Date = F_LDDAT;
        F_AS_PARTNER_HEAD                  : String(8);
        F_AS_PARTNER_NAME_HEAD             : String(40);
        F_AS_PARTNER_ITM                   : String(8);
        F_AS_PARTNER_NAME_ITM              : String(40);
        VBELN_DEL                          : String(10);
        POSNR_DEL                          : String(6);
        CHARG                              : String(10);
        LFIMG                              : Decimal(13, 3);
        VRKME_1                            : String(3);
        POSAR                              : String(1);
        VGBEL                              : String(10);
        VGPOS                              : String(6);
        LFART                              : String(4);
        LFART_VTEXT_LANG                   : String(20);
        LFDAT                              : String(8);
        DL_LFDAT_DATE                      : Date = LFDAT;
        HSDAT                              : String(8);
        DL_HSDAT_DATE                      : Date = HSDAT;
        VFDAT                              : String(8);
        DL_VFDAT_DATE                      : Date = VFDAT;
        TRAID                              : String(20);
        ZZ0S2BLNR                          : String(30);
        PEND_DEL_QUAN                      : String(500);
        WADAT                              : String(8);
        DL_WADAT_DATE                      : Date = WADAT;
        WADAT_IST                          : String(8);
        DL_WADAT_IST_DATE                  : Date = WADAT_IST;
        NOTE_TEXT                          : String(1000);
        LANGUAGE                           : String(2);
        TKNUM                              : String(10);
        VSART                              : String(2);
        VSART_BEZEI_LANG                   : String(20);
        EXTI1                              : String(20);
        TDLNR                              : String(10);
        TDLNR_NAME1                        : String(35);
        STATUS_CODE_ELEM                   : String(3);
        STATUS_REASON_CODE_ELEM            : String(3);
        STATUS_CODE_TEXT_ELEM              : String(255);
        STATUS_REASON_CODE_TEXT_ELEM       : String(255);
        TRACKING_ID_ELEM                   : String(12);
        ALERT_STATUS_CODE_ELEM             : String(3);
        ALERT_STATUS_REASON_CODE_ELEM      : String(3);
        ALERT_STATUS_CODE_TEXT_ELEM        : String(255);
        ALERT_STATUS_REASON_CODE_TEXT_ELEM : String(255);
        STATUS_CODE_COMP                   : String(3);
        REASON_CODE_COMP                   : String(17);
        STATUS_CODE_TEXT_COMP              : String(100);
        REASON_CODE_TEXT_COMP              : String(100);
        TRACKING_ID_COMP                   : String(50);
        STATUS_CODE_MANUEL                 : String(3);
        DPTBG                              : String(8);
        TM_DPTBG_DATE                      : Date = DPTBG;
        DATBG                              : String(8);
        TM_DATBG_DATE                      : Date = DATBG;
        DPTEN                              : String(8);
        TM_DPTEN_DATE                      : Date = DPTEN;
        DATEN                              : String(8);
        TM_DATEN_DATE                      : Date = DATEN;
        AR_DATE                            : String(8);
        TM_AR_DATE_DATE                    : Date = AR_DATE;
        STTRG                              : String(1);
        STTRG_DDTEXT_LANG                  : String(60);
        BL_VBELN_INV_FIRST                 : String(10);
        BL_POSNR_INV_FIRST                 : String(6);
        BL_VBELN_INV_LAST                  : String(10);
        BL_POSNR_INV_LAST                  : String(6);
        XBLNR                              : String(16);
        MANDT_DEL                          : String(3);
        TM_MANDT                           : String(3);
        BL_MANDT_INV_FIRST                 : String(3);
        BL_MANDT_INV_LAST                  : String(3);
        ABGRU_BEZEI_LANG                   : String(40);
        // DCP_ITEM_STATUS                    : String(2);
        ERDAT_DEL                          : String(8);
        ERDAT_DEL_DATE                     : Date = ERDAT_DEL;
        LDDAT_DEL                          : String(8);
        LDDAT_DEL_DATE                     : Date = LDDAT_DEL;
        PERFK                              : String(2);
        PERFK_LTEXT_LANG                   : String(50);

}

entity PARTNER_SETTINGS {
        CLIENT         : String(3);
        BASF_USER      : String(12);
        PARTNER_ROLE   : String(2);
        PARTNER_NUMBER : String(8);
        ACTIVE         : String(1);
        COMMT          : String(50);
}

// type VBAKAuthObjectKeys {
//         VKORG: String(4)  ;
//         VTWEG: String(2)  ;
//         SPART: String(2)  ;
//         UserId: String;
// }
@cds.persistence.exists
entity VBAKAUTH {
        key VKORG  : String(4);
        key VTWEG  : String(2);
        key SPART  : String(2);
        key USERID : String;
        LAST_UPDATE: Timestamp;
}

@cds.persistence.exists

entity ![ST_NOTES] {
        CLIENT         : String(3);
        UTCTIME        : Decimal(15) not null;
        VBELN          : String(10);
        POSNR          : String(6);
        LANGUAGE       : String(2);
        NOTE_TITLE     : String(60);
        NOTE_TEXT      : String(1000);
        USERNAME       : String(12);
        LAST_NOTE_FLAG : String(1);
}
