namespace allorders.db;

@cds.persistence.exists
entity ![RESULTS] {
        ID                                    : String(1);
        SO_MANDT                              : String(3);
        SO_VBELN                              : String(10);
        SO_POSNR                              : String(6);
        SO_ERDAT_ORDER                        : String(8);
        SO_ERDAT_ORDER_DATE : Date = SUBSTRING(SO_ERDAT_ORDER, 1, 4) || '-' ||  SUBSTRING(SO_ERDAT_ORDER, 5, 2) || '-' || SUBSTRING(SO_ERDAT_ORDER, 7, 2);
        SO_ERDAT_ITEM                         : String(8);
        SO_ERDAT_ITEM_DATE : Date = SUBSTRING(SO_ERDAT_ITEM, 1, 4) || '-' ||  SUBSTRING(SO_ERDAT_ITEM, 5, 2) || '-' || SUBSTRING(SO_ERDAT_ITEM, 7, 2);
        SO_AUART                              : String(4);
        SO_WERKS                              : String(4);
        SO_VTWEG                              : String(2);
        SO_MATNR                              : String(18);
        SO_MAKTX                              : String(40);
        SO_KDMAT                              : String(35);
        SO_AG_PARTNER                         : String(10);
        SO_AG_PARTNER_NAME1                   : String(35);
        SO_AG_PARTNER_NAME2                   : String(35);
        SO_WE_PARTNER                         : String(10);
        SO_WE_PARTNER_NAME1                   : String(35);
        SO_WE_PARTNER_NAME2                   : String(35);
        SO_CO_PARTNER_HEAD                    : String(10);
        SO_CO_PARTNER_NAME1_HEAD              : String(35);
        SO_CO_PARTNER_NAME2_HEAD              : String(35);
        SO_CO_PARTNER_ITM                     : String(10);
        SO_CO_PARTNER_NAME1_ITM               : String(35);
        SO_CO_PARTNER_NAME2_ITM               : String(35);
        SO_NY_PARTNER_HEAD                    : String(10);
        SO_NY_PARTNER_NAME1_HEAD              : String(35);
        SO_NY_PARTNER_NAME2_HEAD              : String(35);
        SO_NY_PARTNER_ITM                     : String(10);
        SO_NY_PARTNER_NAME1_ITM               : String(35);
        SO_NY_PARTNER_NAME2_ITM               : String(35);
        SO_AS_PARTNER_HEAD                    : String(8);
        SO_AS_PARTNER_NAME_HEAD               : String(40);
        SO_AS_PARTNER_ITM                     : String(8);
        SO_AS_PARTNER_NAME_ITM                : String(40);
        SO_VE_PARTNER_HEAD                    : String(8);
        SO_VE_PARTNER_NAME_HEAD               : String(40);
        SO_VE_PARTNER_ITM                     : String(8);
        SO_VE_PARTNER_NAME_ITM                : String(40);
        SO_AM_PARTNER_HEAD                    : String(8);
        SO_AM_PARTNER_NAME_HEAD               : String(40);
        SO_AM_PARTNER_ITM                     : String(8);
        SO_AM_PARTNER_NAME_ITM                : String(40);
        SO_LAND1                              : String(3);
        SO_LANDX                              : String(15);
        SO_ORT01                              : String(35);
        SO_VKORG                              : String(4);
        SO_VKORG_NAME1                        : String(40);
        SO_KNREF_HEAD                         : String(30);
        SO_KNREF_ITM                          : String(30);
        SO_VBUND                              : String(6);
        SO_EDATU_REQUESTED                    : String(8);
        SO_EDATU_REQUESTED_DATE : Date = SUBSTRING(SO_EDATU_REQUESTED, 1, 4) || '-' ||  SUBSTRING(SO_EDATU_REQUESTED, 5, 2) || '-' || SUBSTRING(SO_EDATU_REQUESTED, 7, 2);
        SO_KWMENG                             : Decimal(15, 3);
        SO_VRKME                              : String(3);
        SO_EDATU_CONFIRMED                    : String(8);
        SO_EDATU_CONFIRMED_DATE : Date = SUBSTRING(SO_EDATU_CONFIRMED, 1, 4) || '-' ||  SUBSTRING(SO_EDATU_CONFIRMED, 5, 2) || '-' || SUBSTRING(SO_EDATU_CONFIRMED, 7, 2);
        SO_KBMENG                             : Decimal(15, 3);
        SO_UNCONFIRMED_QTY                    : Decimal(15, 3);
        SO_REQ_TEXT                           : String(250);
        SO_FAKSP                              : String(2);
        SO_FAKSP_VTEXT                        : String(20);
        SO_LGORT                              : String(4);
        SO_SUPPLY_SITUATION                   : Int16;
        SO_SUPPLY_SITUATION_DESCR             : String(60);
        SO_KBETR                              : Decimal(11, 2);
        SO_KBETR_ALT                          : Decimal(11, 2);
        SO_WAERS                              : String(5);
        SO_WAERS_ALT                          : String(5);
        SO_KPEIN                              : Decimal(5);
        SO_KPEIN_ALT                          : Decimal(5);
        SO_KMEIN                              : String(3);
        SO_KMEIN_ALT                          : String(3);
        SO_NETWR                              : Decimal(15, 2);
        SO_WAERK                              : String(5);
        SO_HTEXT                              : String(4000);
        SO_PSTYV                              : String(4);
        SO_PSTYV_VTEXT                        : String(20);
        SO_DISPO                              : String(3);
        SO_KOSCH                              : String(18);
        SO_VKBUR                              : String(4);
        SO_VKBUR_BEZEI                        : String(20);
        SO_ABGRU                              : String(2);
        SO_ABSTA                              : String(1);
        SO_KNUMV                              : String(10);
        SO_SPART                              : String(2);
        SO_INCO1_HEAD                         : String(3);
        SO_INCO1_ITEM                         : String(3);
        SO_INCO2_HEAD                         : String(28);
        SO_INCO2_ITEM                         : String(28);
        SO_ZTERM_HEAD                         : String(4);
        SO_ZTERM_ITEM                         : String(4);
        SO_PRSDT                              : String(8);
        SO_PRSDT_DATE : Date = SUBSTRING(SO_PRSDT, 1, 4) || '-' ||  SUBSTRING(SO_PRSDT, 5, 2) || '-' || SUBSTRING(SO_PRSDT, 7, 2);
        SO_ZZ0S2REVG2                         : String(10);
        SO_ZZDKPPRODB                         : String(18);
        SO_BSARK                              : String(4);
        SO_BSARK_VTEXT                        : String(20);
        SO_BASF_LOFCR                         : String(20);
        SO_GUSCON                             : String(15);
        SO_GUSCON_ITM                         : String(6);
        SO_GUSCON_LEVEL                       : String(2);
        SO_I_VBELN                            : String(10);
        SO_I_POSNR                            : String(6);
        SO_ISCOMPLETED                        : String(1);
        SO_LEVEL_TYPE                         : String(1);
        SO_N_VBELN                            : String(10);
        SO_N_POSNR                            : String(6);
        SO_F_VBELN                            : String(10);
        SO_F_POSNR                            : String(6);
        SO_VBTYP                              : String(1);
        SO_BSTKD                              : String(35);
        SO_TRAGR                              : String(4);
        SO_TRAGR_VTEXT                        : String(20);
        SO_VKGRP                              : String(3);
        SO_VKGRP_BEZEI                        : String(20);
        SO_ROUTE                              : String(6);
        SO_FAKSK                              : String(2);
        SO_FAKSK_VTEXT                        : String(20);
        SO_F_WERKS                            : String(4);
        SO_F_VKORG                            : String(4);
        SO_F_VKORG_VTEXT                      : String(40);
        SO_F_TDDAT                            : String(8);
        SO_F_TDDAT_DATE : Date = SUBSTRING(SO_F_TDDAT, 1, 4) || '-' ||  SUBSTRING(SO_F_TDDAT, 5, 2) || '-' || SUBSTRING(SO_F_TDDAT, 7, 2);
        SO_F_ZZ0S2MATUG                       : String(18);
        SO_F_VSBED                            : String(2);
        SO_F_VSBED_VTEXT                      : String(20);
        SO_F_AUFNR                            : String(12);
        SO_F_DGLTP                            : String(8);
        SO_F_DGLTP_DATE : Date = SUBSTRING(SO_F_DGLTP, 1, 4) || '-' ||  SUBSTRING(SO_F_DGLTP, 5, 2) || '-' || SUBSTRING(SO_F_DGLTP, 7, 2);
        SO_F_PSMNG                            : Decimal(13, 3);
        SO_F_AMEIN                            : String(3);
        SO_F_LDDAT                            : String(8);
        SO_F_LDDAT_DATE : Date = SUBSTRING(SO_F_LDDAT, 1, 4) || '-' ||  SUBSTRING(SO_F_LDDAT, 5, 2) || '-' || SUBSTRING(SO_F_LDDAT, 7, 2);
        SO_F_AS_PARTNER_HEAD                  : String(8);
        SO_F_AS_PARTNER_NAME_HEAD             : String(40);
        SO_F_AS_PARTNER_ITM                   : String(8);
        SO_F_AS_PARTNER_NAME_ITM              : String(40);
        DL_VBELN                              : String(10);
        DL_POSNR                              : String(6);
        DL_CHARG                              : String(10);
        DL_LFIMG                              : Decimal(13, 3);
        DL_VRKME                              : String(3);
        DL_POSAR                              : String(1);
        DL_VGBEL                              : String(10);
        DL_VGPOS                              : String(6);
        DL_LFART                              : String(4);
        DL_LFART_VTEXT                        : String(20);
        DL_LFDAT                              : String(8);
        DL_LFDAT_DATE : Date = SUBSTRING(DL_LFDAT, 1, 4) || '-' ||  SUBSTRING(DL_LFDAT, 5, 2) || '-' || SUBSTRING(DL_LFDAT, 7, 2);
        DL_HSDAT                              : String(8);
        DL_HSDAT_DATE : Date = SUBSTRING(DL_HSDAT, 1, 4) || '-' ||  SUBSTRING(DL_HSDAT, 5, 2) || '-' || SUBSTRING(DL_HSDAT, 7, 2);
        DL_VFDAT                              : String(8);
        DL_VFDAT_DATE : Date = SUBSTRING(DL_VFDAT, 1, 4) || '-' ||  SUBSTRING(DL_VFDAT, 5, 2) || '-' || SUBSTRING(DL_VFDAT, 7, 2);
        DL_TRAID                              : String(20);
        DL_ZZ0S2BLNR                          : String(30);
        DL_PEND_DEL_QUAN                      : String(500);
        DL_WADAT                              : String(8);
        DL_WADAT_DATE : Date = SUBSTRING(DL_WADAT, 1, 4) || '-' ||  SUBSTRING(DL_WADAT, 5, 2) || '-' || SUBSTRING(DL_WADAT, 7, 2);
        DL_WADAT_IST                          : String(8);
        DL_WADAT_IST_DATE : Date = SUBSTRING(DL_WADAT_IST, 1, 4) || '-' ||  SUBSTRING(DL_WADAT_IST, 5, 2) || '-' || SUBSTRING(DL_WADAT_IST, 7, 2);
        LAST_NOTE                             : String(1000);
        LANGUAGE                              : String(2);
        TM_TKNUM                              : String(10);
        TM_VSART                              : String(2);
        TM_VSART_BEZEI                        : String(20);
        TM_EXTI1                              : String(20);
        TM_TDLNR                              : String(10);
        TM_TDLNR_NAME1                        : String(35);
        TM_STATUS_CODE_ELEM                   : String(3);
        TM_STATUS_REASON_CODE_ELEM            : String(3);
        TM_STATUS_CODE_TEXT_ELEM              : String(255);
        TM_STATUS_REASON_CODE_TEXT_ELEM       : String(255);
        TM_TRACKING_ID_ELEM                   : String(12);
        TM_ALERT_STATUS_CODE_ELEM             : String(3);
        TM_ALERT_STATUS_REASON_CODE_ELEM      : String(3);
        TM_ALERT_STATUS_CODE_TEXT_ELEM        : String(255);
        TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM : String(255);
        TM_STATUS_CODE_COMP                   : String(3);
        TM_REASON_CODE_COMP                   : String(17);
        TM_STATUS_CODE_TEXT_COMP              : String(100);
        TM_REASON_CODE_TEXT_COMP              : String(100);
        TM_TRACKING_ID_COMP                   : String(50);
        TM_STATUS_CODE_MANUEL                 : String(3);
        TM_DPTBG                              : String(8);
        TM_DPTBG_DATE : Date = SUBSTRING(TM_DPTBG, 1, 4) || '-' ||  SUBSTRING(TM_DPTBG, 5, 2) || '-' || SUBSTRING(TM_DPTBG, 7, 2);
        TM_DATBG                              : String(8);
        TM_DATBG_DATE : Date = SUBSTRING(TM_DATBG, 1, 4) || '-' ||  SUBSTRING(TM_DATBG, 5, 2) || '-' || SUBSTRING(TM_DATBG, 7, 2);
        TM_DPTEN                              : String(8);
        TM_DPTEN_DATE : Date = SUBSTRING(TM_DPTEN, 1, 4) || '-' ||  SUBSTRING(TM_DPTEN, 5, 2) || '-' || SUBSTRING(TM_DPTEN, 7, 2);
        TM_DATEN                              : String(8);
        TM_DATEN_DATE : Date = SUBSTRING(TM_DATEN, 1, 4) || '-' ||  SUBSTRING(TM_DATEN, 5, 2) || '-' || SUBSTRING(TM_DATEN, 7, 2);
        TM_AR_DATE                            : String(8);
        TM_AR_DATE_DATE : Date = SUBSTRING(TM_AR_DATE, 1, 4) || '-' ||  SUBSTRING(TM_AR_DATE, 5, 2) || '-' || SUBSTRING(TM_AR_DATE, 7, 2);
        TM_STTRG                              : String(1);
        TM_STTRG_DDTEXT                       : String(60);
        BL_VBELN_INV_FIRST                    : String(10);
        BL_VBELN_INV_LAST                     : String(10);
        BL_XBLNR                              : String(16);
        
}

entity PARTNER_SETTINGS {
        CLIENT         : String(3);
        BASF_USER      : String(12);
        PARTNER_ROLE   : String(2);
        PARTNER_NUMBER : String(8);
        ACTIVE         : String(1);
        COMMT          : String(50);
}

// type VBAKAuthObjectKeys {
//         VKORG: String(4)  ; 
//         VTWEG: String(2)  ;
//         SPART: String(2)  ;
//         UserId: String;
// }
@cds.persistence.exists
entity VBAKAUTH {
        key VKORG: String(4)  ; 
        key VTWEG: String(2)  ;
        key SPART: String(2)  ;
        key USERID: String;
}

@cds.persistence.exists 
entity ![ORDERLIST_COUNT]{
        SO_MANDT                              : String(3);
        SO_VBELN                              : String(10);
        SO_POSNR                              : String(6);
        SO_ERDAT_ORDER                        : String(8);
        SO_ERDAT_ORDER_DATE : Date = SUBSTRING(SO_ERDAT_ORDER, 1, 4) || '-' ||  SUBSTRING(SO_ERDAT_ORDER, 5, 2) || '-' || SUBSTRING(SO_ERDAT_ORDER, 7, 2);
        SO_ERDAT_ITEM                         : String(8);
        SO_ERDAT_ITEM_DATE : Date = SUBSTRING(SO_ERDAT_ITEM, 1, 4) || '-' ||  SUBSTRING(SO_ERDAT_ITEM, 5, 2) || '-' || SUBSTRING(SO_ERDAT_ITEM, 7, 2);
        SO_AUART                              : String(4);
        SO_WERKS                              : String(4);
        SO_VTWEG                              : String(2);
        SO_MATNR                              : String(18);
        SO_MAKTX                              : String(40);
        SO_KDMAT                              : String(35);
        SO_AG_PARTNER                         : String(10);
        SO_AG_PARTNER_NAME1                   : String(35);
        SO_AG_PARTNER_NAME2                   : String(35);
        SO_WE_PARTNER                         : String(10);
        SO_WE_PARTNER_NAME1                   : String(35);
        SO_WE_PARTNER_NAME2                   : String(35);
        SO_CO_PARTNER_HEAD                    : String(10);
        SO_CO_PARTNER_NAME1_HEAD              : String(35);
        SO_CO_PARTNER_NAME2_HEAD              : String(35);
        SO_CO_PARTNER_ITM                     : String(10);
        SO_CO_PARTNER_NAME1_ITM               : String(35);
        SO_CO_PARTNER_NAME2_ITM               : String(35);
        SO_NY_PARTNER_HEAD                    : String(10);
        SO_NY_PARTNER_NAME1_HEAD              : String(35);
        SO_NY_PARTNER_NAME2_HEAD              : String(35);
        SO_NY_PARTNER_ITM                     : String(10);
        SO_NY_PARTNER_NAME1_ITM               : String(35);
        SO_NY_PARTNER_NAME2_ITM               : String(35);
        SO_AS_PARTNER_HEAD                    : String(8);
        SO_AS_PARTNER_NAME_HEAD               : String(40);
        SO_AS_PARTNER_ITM                     : String(8);
        SO_AS_PARTNER_NAME_ITM                : String(40);
        SO_VE_PARTNER_HEAD                    : String(8);
        SO_VE_PARTNER_NAME_HEAD               : String(40);
        SO_VE_PARTNER_ITM                     : String(8);
        SO_VE_PARTNER_NAME_ITM                : String(40);
        SO_AM_PARTNER_HEAD                    : String(8);
        SO_AM_PARTNER_NAME_HEAD               : String(40);
        SO_AM_PARTNER_ITM                     : String(8);
        SO_AM_PARTNER_NAME_ITM                : String(40);
        SO_LAND1                              : String(3);
        SO_LANDX                              : String(15);
        SO_ORT01                              : String(35);
        SO_VKORG                              : String(4);
        SO_VKORG_NAME1                        : String(40);
        SO_KNREF_HEAD                         : String(30);
        SO_KNREF_ITM                          : String(30);
        SO_VBUND                              : String(6);
        SO_EDATU_REQUESTED                    : String(8);
        SO_EDATU_REQUESTED_DATE : Date = SUBSTRING(SO_EDATU_REQUESTED, 1, 4) || '-' ||  SUBSTRING(SO_EDATU_REQUESTED, 5, 2) || '-' || SUBSTRING(SO_EDATU_REQUESTED, 7, 2);
        SO_KWMENG                             : Decimal(15, 3);
        SO_VRKME                              : String(3);
        SO_EDATU_CONFIRMED                    : String(8);
        SO_EDATU_CONFIRMED_DATE : Date = SUBSTRING(SO_EDATU_CONFIRMED, 1, 4) || '-' ||  SUBSTRING(SO_EDATU_CONFIRMED, 5, 2) || '-' || SUBSTRING(SO_EDATU_CONFIRMED, 7, 2);
        SO_KBMENG                             : Decimal(15, 3);
        SO_UNCONFIRMED_QTY                    : Decimal(15, 3);
        SO_REQ_TEXT                           : String(250);
        SO_FAKSP                              : String(2);
        SO_FAKSP_VTEXT                        : String(20);
        SO_LGORT                              : String(4);
        SO_SUPPLY_SITUATION                   : Int16;
        SO_SUPPLY_SITUATION_DESCR             : String(60);
        SO_KBETR                              : Decimal(11, 2);
        SO_KBETR_ALT                          : Decimal(11, 2);
        SO_WAERS                              : String(5);
        SO_WAERS_ALT                          : String(5);
        SO_KPEIN                              : Decimal(5);
        SO_KPEIN_ALT                          : Decimal(5);
        SO_KMEIN                              : String(3);
        SO_KMEIN_ALT                          : String(3);
        SO_NETWR                              : Decimal(15, 2);
        SO_WAERK                              : String(5);
        SO_HTEXT                              : String(4000);
        SO_PSTYV                              : String(4);
        SO_PSTYV_VTEXT                        : String(20);
        SO_DISPO                              : String(3);
        SO_KOSCH                              : String(18);
        SO_VKBUR                              : String(4);
        SO_VKBUR_BEZEI                        : String(20);
        SO_ABGRU                              : String(2);
        SO_ABSTA                              : String(1);
        SO_KNUMV                              : String(10);
        SO_SPART                              : String(2);
        SO_INCO1_HEAD                         : String(3);
        SO_INCO1_ITEM                         : String(3);
        SO_INCO2_HEAD                         : String(28);
        SO_INCO2_ITEM                         : String(28);
        SO_ZTERM_HEAD                         : String(4);
        SO_ZTERM_ITEM                         : String(4);
        SO_PRSDT                              : String(8);
        SO_PRSDT_DATE : Date = SUBSTRING(SO_PRSDT, 1, 4) || '-' ||  SUBSTRING(SO_PRSDT, 5, 2) || '-' || SUBSTRING(SO_PRSDT, 7, 2);
        SO_ZZ0S2REVG2                         : String(10);
        SO_ZZDKPPRODB                         : String(18);
        SO_BSARK                              : String(4);
        SO_BSARK_VTEXT                        : String(20);
        SO_BASF_LOFCR                         : String(20);
        SO_GUSCON                             : String(15);
        SO_GUSCON_ITM                         : String(6);
        SO_GUSCON_LEVEL                       : String(2);
        SO_I_VBELN                            : String(10);
        SO_I_POSNR                            : String(6);
        SO_ISCOMPLETED                        : String(1);
        SO_LEVEL_TYPE                         : String(1);
        SO_N_VBELN                            : String(10);
        SO_N_POSNR                            : String(6);
        SO_F_VBELN                            : String(10);
        SO_F_POSNR                            : String(6);
        SO_VBTYP                              : String(1);
        SO_BSTKD                              : String(35);
        SO_TRAGR                              : String(4);
        SO_TRAGR_VTEXT                        : String(20);
        SO_VKGRP                              : String(3);
        SO_VKGRP_BEZEI                        : String(20);
        SO_ROUTE                              : String(6);
        SO_FAKSK                              : String(2);
        SO_FAKSK_VTEXT                        : String(20);
        SO_F_WERKS                            : String(4);
        SO_F_VKORG                            : String(4);
        SO_F_VKORG_VTEXT                      : String(40);
        SO_F_TDDAT                            : String(8);
        SO_F_TDDAT_DATE : Date = SUBSTRING(SO_F_TDDAT, 1, 4) || '-' ||  SUBSTRING(SO_F_TDDAT, 5, 2) || '-' || SUBSTRING(SO_F_TDDAT, 7, 2);
        SO_F_ZZ0S2MATUG                       : String(18);
        SO_F_VSBED                            : String(2);
        SO_F_VSBED_VTEXT                      : String(20);
        SO_F_AUFNR                            : String(12);
        SO_F_DGLTP                            : String(8);
        SO_F_DGLTP_DATE : Date = SUBSTRING(SO_F_DGLTP, 1, 4) || '-' ||  SUBSTRING(SO_F_DGLTP, 5, 2) || '-' || SUBSTRING(SO_F_DGLTP, 7, 2);
        SO_F_PSMNG                            : Decimal(13, 3);
        SO_F_AMEIN                            : String(3);
        SO_F_LDDAT                            : String(8);
        SO_F_LDDAT_DATE : Date = SUBSTRING(SO_F_LDDAT, 1, 4) || '-' ||  SUBSTRING(SO_F_LDDAT, 5, 2) || '-' || SUBSTRING(SO_F_LDDAT, 7, 2);
        SO_F_AS_PARTNER_HEAD                  : String(8);
        SO_F_AS_PARTNER_NAME_HEAD             : String(40);
        SO_F_AS_PARTNER_ITM                   : String(8);
        SO_F_AS_PARTNER_NAME_ITM              : String(40);
        DL_VBELN                              : String(10);
        DL_POSNR                              : String(6);
        DL_CHARG                              : String(10);
        DL_LFIMG                              : Decimal(13, 3);
        DL_VRKME                              : String(3);
        DL_POSAR                              : String(1);
        DL_VGBEL                              : String(10);
        DL_VGPOS                              : String(6);
        DL_LFART                              : String(4);
        DL_LFART_VTEXT                        : String(20);
        DL_LFDAT                              : String(8);
        DL_LFDAT_DATE : Date = SUBSTRING(DL_LFDAT, 1, 4) || '-' ||  SUBSTRING(DL_LFDAT, 5, 2) || '-' || SUBSTRING(DL_LFDAT, 7, 2);
        DL_HSDAT                              : String(8);
        DL_HSDAT_DATE : Date = SUBSTRING(DL_HSDAT, 1, 4) || '-' ||  SUBSTRING(DL_HSDAT, 5, 2) || '-' || SUBSTRING(DL_HSDAT, 7, 2);
        DL_VFDAT                              : String(8);
        DL_VFDAT_DATE : Date = SUBSTRING(DL_VFDAT, 1, 4) || '-' ||  SUBSTRING(DL_VFDAT, 5, 2) || '-' || SUBSTRING(DL_VFDAT, 7, 2);
        DL_TRAID                              : String(20);
        DL_ZZ0S2BLNR                          : String(30);
        DL_PEND_DEL_QUAN                      : String(500);
        DL_WADAT                              : String(8);
        DL_WADAT_DATE : Date = SUBSTRING(DL_WADAT, 1, 4) || '-' ||  SUBSTRING(DL_WADAT, 5, 2) || '-' || SUBSTRING(DL_WADAT, 7, 2);
        DL_WADAT_IST                          : String(8);
        DL_WADAT_IST_DATE : Date = SUBSTRING(DL_WADAT_IST, 1, 4) || '-' ||  SUBSTRING(DL_WADAT_IST, 5, 2) || '-' || SUBSTRING(DL_WADAT_IST, 7, 2);
        LAST_NOTE                             : String(1000);
        LANGUAGE                              : String(2);
        TM_TKNUM                              : String(10);
        TM_VSART                              : String(2);
        TM_VSART_BEZEI                        : String(20);
        TM_EXTI1                              : String(20);
        TM_TDLNR                              : String(10);
        TM_TDLNR_NAME1                        : String(35);
        TM_STATUS_CODE_ELEM                   : String(3);
        TM_STATUS_REASON_CODE_ELEM            : String(3);
        TM_STATUS_CODE_TEXT_ELEM              : String(255);
        TM_STATUS_REASON_CODE_TEXT_ELEM       : String(255);
        TM_TRACKING_ID_ELEM                   : String(12);
        TM_ALERT_STATUS_CODE_ELEM             : String(3);
        TM_ALERT_STATUS_REASON_CODE_ELEM      : String(3);
        TM_ALERT_STATUS_CODE_TEXT_ELEM        : String(255);
        TM_ALERT_STATUS_REASON_CODE_TEXT_ELEM : String(255);
        TM_STATUS_CODE_COMP                   : String(3);
        TM_REASON_CODE_COMP                   : String(17);
        TM_STATUS_CODE_TEXT_COMP              : String(100);
        TM_REASON_CODE_TEXT_COMP              : String(100);
        TM_TRACKING_ID_COMP                   : String(50);
        TM_STATUS_CODE_MANUEL                 : String(3);
        TM_DPTBG                              : String(8);
        TM_DPTBG_DATE : Date = SUBSTRING(TM_DPTBG, 1, 4) || '-' ||  SUBSTRING(TM_DPTBG, 5, 2) || '-' || SUBSTRING(TM_DPTBG, 7, 2);
        TM_DATBG                              : String(8);
        TM_DATBG_DATE : Date = SUBSTRING(TM_DATBG, 1, 4) || '-' ||  SUBSTRING(TM_DATBG, 5, 2) || '-' || SUBSTRING(TM_DATBG, 7, 2);
        TM_DPTEN                              : String(8);
        TM_DPTEN_DATE : Date = SUBSTRING(TM_DPTEN, 1, 4) || '-' ||  SUBSTRING(TM_DPTEN, 5, 2) || '-' || SUBSTRING(TM_DPTEN, 7, 2);
        TM_DATEN                              : String(8);
        TM_DATEN_DATE : Date = SUBSTRING(TM_DATEN, 1, 4) || '-' ||  SUBSTRING(TM_DATEN, 5, 2) || '-' || SUBSTRING(TM_DATEN, 7, 2);
        TM_AR_DATE                            : String(8);
        TM_AR_DATE_DATE : Date = SUBSTRING(TM_AR_DATE, 1, 4) || '-' ||  SUBSTRING(TM_AR_DATE, 5, 2) || '-' || SUBSTRING(TM_AR_DATE, 7, 2);
        TM_STTRG                              : String(1);
        TM_STTRG_DDTEXT                       : String(60);
        BL_VBELN_INV_FIRST                    : String(10);
        BL_VBELN_INV_LAST                     : String(10);
        BL_XBLNR                              : String(16);
}
