using openOrdersSrv as service from '../../srv/order-monitoring-amoo-services.cds';

// ------------- different tabs qualifier for lineitems-------

annotate service.allIssues with @UI.LineItem #allIssues: {
    ![@UI.Criticality]: 5,
    $value            : [
        {Value: SO_VBELN},
        {Value: SO_POSNR},
        {Value: SO_DUE_DATE},
        {Value: SO_NPS},
        {Value: SO_ISSUE},
        {Value: SO_ERDAT_ITEM},
        {Value: SO_WE_PARTNER_NAME},
        {Value: SO_LAND1},
        {Value: SO_LANDX},
        {Value: SO_ORT01},
        {Value: SO_WERKS},
        {Value: SO_MAKTX},
        {Value: SO_MATNR},
        {Value: SO_KDMAT},
        {Value: SO_EDATU_REQUESTED},
        {Value: SO_EDATU_CONFIRMED},
        {Value: SO_ZZDKPPRODB},
        {Value: DL_VBELN},
        {Value: DL_POSNR},
        {Value: TM_TKNUM},
        {Value: DL_WADAT_IST},
        {Value: TM_TDLNR},
        {Value: TM_TDLNR_NAME1},
        {Value: SO_VKORG},
        {Value: SO_VTWEG},
        {Value: SO_KWMENG},
        {Value: SO_KBMENG},
        {Value: SO_NETWR},
        {Value: SO_KBETR},
        {Value: SO_ROUTE},
        {Value: SO_F_LDDAT},
        {Value: TM_DPTBG},
        {Value: TM_DPTEN},
        {Value: TM_DATBG},
        {Value: TM_DATEN},
        {Value: TM_SHIPMENT_CURRENT_STATUS},
        {Value: TM_VISTA_STATUS}
    ]
};

annotate service.allIssues with @UI.LineItem #nps10: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_AUART},
    {Value: SO_VTWEG},
    {Value: SO_WERKS},
    {Value: SO_MAKTX},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_KDMAT},
    {Value: SO_ERDAT_ORDER},
    {Value: SO_ERDAT_ITEM},
    {Value: SO_MATNR},
    {Value: SO_AG_PARTNER},
    {Value: SO_AG_PARTNER_NAME},
    {Value: SO_WE_PARTNER},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_LANDX},
    {Value: SO_ORT01},
    {Value: SO_VKORG},
    {Value: SO_VKORG_NAME1},
    {Value: SO_VKBUR},
    {Value: SO_VKBUR_BEZEI},
    {Value: SO_NETWR},
    {Value: SO_BSTKD},
    {Value: SO_EDATU_REQUESTED},
    {Value: SO_KWMENG}
]};

annotate service.allIssues with @UI.LineItem #nps20: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_WERKS},
    {Value: SO_MAKTX},
    {Value: SO_KDMAT},
    {Value: SO_ERDAT_ORDER},
    {Value: SO_ERDAT_ITEM},
    {Value: SO_AUART},
    {Value: SO_VTWEG},
    {Value: SO_MATNR},
    {Value: SO_AG_PARTNER},
    {Value: SO_AG_PARTNER_NAME},
    {Value: SO_WE_PARTNER},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_LANDX},
    {Value: SO_ORT01},
    {Value: SO_VKORG},
    {Value: SO_VKORG_NAME1},
    {Value: SO_EDATU_REQUESTED},
    {Value: SO_KWMENG},
    {Value: SO_VRKME},
    {Value: SO_BSTKD},
    {Value: SO_F_WERKS},
    {Value: SO_ZZ0S2REVG2},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_ZTERM},
    {Value: SO_PRSDT},
    {Value: SO_KBETR},
    {Value: SO_WAERS},
    {Value: SO_SPART},
    {Value: SO_GUSCON_LEVEL},
    {Value: SO_I_VBELN},
    {Value: SO_LEVEL_TYPE},
    {Value: SO_N_VBELN},
    {Value: SO_F_VBELN}

]};

annotate service.allIssues with @UI.LineItem #nps30: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_MAKTX},
    {Value: SO_WERKS},
    {Value: SO_KDMAT},
    {Value: SO_ERDAT_ORDER},
    {Value: SO_ERDAT_ITEM},
    {Value: SO_AUART},
    {Value: SO_VTWEG},
    {Value: SO_MATNR},
    {Value: SO_AG_PARTNER},
    {Value: SO_AG_PARTNER_NAME},
    {Value: SO_WE_PARTNER},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_LANDX},
    {Value: SO_ORT01},
    {Value: SO_VKORG},
    {Value: SO_VKORG_NAME1},
    {Value: SO_EDATU_REQUESTED},
    {Value: SO_KWMENG},
    {Value: SO_VRKME},
    {Value: SO_BSTKD},
    {Value: SO_F_WERKS},
    {Value: SO_ZZ0S2REVG2},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_KBETR},
    {Value: SO_WAERS},
    {Value: SO_NETWR},
    {Value: SO_ZTERM},
    {Value: SO_PRSDT},
    {Value: SO_SPART},
    {Value: SO_GUSCON_LEVEL},
    {Value: SO_I_VBELN},
    {Value: SO_LEVEL_TYPE},
    {Value: SO_N_VBELN},
    {Value: SO_F_VBELN}
]};

annotate service.allIssues with @UI.LineItem #nps40: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_WERKS},
    {Value: SO_MAKTX},
    {Value: SO_KDMAT},
    {Value: SO_ERDAT_ORDER},
    {Value: SO_ERDAT_ITEM},
    {Value: SO_AUART},
    {Value: SO_VTWEG},
    {Value: SO_MATNR},
    {Value: SO_AG_PARTNER},
    {Value: SO_AG_PARTNER_NAME},
    {Value: SO_WE_PARTNER},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_LANDX},
    {Value: SO_ORT01},
    {Value: SO_VKORG},
    {Value: SO_VKORG_NAME1},
    {Value: SO_EDATU_CONFIRMED},
    {Value: SO_EDATU_REQUESTED},
    {Value: SO_KWMENG},
    {Value: SO_VRKME},
    {Value: SO_BSTKD},
    {Value: SO_F_WERKS},
    {Value: SO_ZZ0S2REVG2},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_KBETR},
    {Value: SO_WAERS},
    {Value: SO_SPART},
    {Value: SO_GUSCON_LEVEL},
    {Value: SO_I_VBELN},
    {Value: SO_LEVEL_TYPE},
    {Value: SO_N_VBELN},
    {Value: SO_F_VBELN},
    {Value: SO_ZTERM},
    {Value: SO_PRSDT}
]};

annotate service.allIssues with @UI.LineItem #nps50: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_MAKTX},
    {Value: SO_MATNR},
    {Value: SO_WERKS},
    {Value: DL_CHARG},
    {Value: DL_VBELN},
    {Value: DL_POSNR},
    {Value: DL_LFDAT},
    {Value: SO_EDATU_CONFIRMED},
    {Value: SO_KWMENG},
    {Value: SO_KBMENG},
    {Value: DL_PEND_DEL_QUAN},
    {Value: DL_WADAT},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_LANDX},
    {Value: SO_ORT01},
    {Value: SO_ROUTE},
    {Value: SO_INCO1},
    {Value: SO_KBETR},
    {Value: SO_NETWR},
    {Value: SO_ZZDKPPRODB}

]};

annotate service.allIssues with @UI.LineItem #nps60: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_MAKTX},
    {Value: SO_MATNR},
    {Value: SO_WERKS},
    {Value: DL_CHARG},
    {Value: TM_TKNUM},
    {Value: TM_VSART},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_ORT01},
    {Value: SO_LAND1},
    {Value: DL_VBELN},
    {Value: SO_WE_PARTNER},
    {Value: DL_LFART},
    {Value: SO_KWMENG},
    {Value: SO_KBMENG},
    {Value: DL_PEND_DEL_QUAN},
    {Value: DL_LFDAT},
    {Value: DL_WADAT},
    {Value: SO_FAKSP},
    {Value: DL_ZZ0S2BLNR},
    {Value: TM_AR_DATE}

]};

annotate service.allIssues with @UI.LineItem #nps70: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_MAKTX},
    {Value: SO_MATNR},
    {Value: SO_WERKS},
    {Value: DL_CHARG},
    {Value: TM_TKNUM},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_ORT01},
    {Value: SO_LAND1},
    {Value: SO_WE_PARTNER},
    {Value: SO_NETWR},
    {Value: DL_VBELN},
    {Value: SO_KWMENG},
    {Value: SO_KBMENG},
    {Value: DL_PEND_DEL_QUAN},
    {Value: DL_LFDAT},
    {Value: DL_WADAT},
    {Value: TM_DPTEN},
    {Value: TM_DPTBG},
    {Value: SO_EDATU_CONFIRMED},
    {Value: DL_TRAID},
    {Value: SO_F_LDDAT},
    {Value: TM_TDLNR_NAME1},
    {Value: SO_INCO1},
    {Value: SO_ROUTE},
    {Value: SO_AUGRU}

]};

annotate service.allIssues with @UI.LineItem #nps80: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_MAKTX},
    {Value: SO_MATNR},
    {Value: SO_WERKS},
    {Value: DL_CHARG},
    {Value: TM_TKNUM},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_ORT01},
    {Value: SO_LAND1},
    {Value: SO_WE_PARTNER},
    {Value: SO_F_VSBED_VTEXT},
    {Value: TM_TDLNR_NAME1},
    {Value: TM_EXTI1},
    {Value: DL_TRAID},
    {Value: SO_ROUTE},
    {Value: DL_VBELN},
    {Value: DL_WADAT},
    {Value: DL_WADAT_IST},
    {Value: SO_KBMENG},
    {Value: TM_DPTEN},
    {Value: TM_DPTBG},
    {Value: SO_EDATU_CONFIRMED},
    {Value: DL_PEND_DEL_QUAN},
    {Value: SO_F_LDDAT},
    {Value: SO_NETWR},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_INCO1}

]};

annotate service.allIssues with @UI.LineItem #nps90: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_MAKTX},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_ORT01},
    {Value: SO_LAND1},
    {Value: DL_VBELN},
    {Value: SO_ZZDKPPRODB},
    {Value: DL_POSNR},
    {Value: TM_SHIPMENT_CURRENT_STATUS},
    // {Value: TM_SHIPMENT_ALERT},
    {Value: TM_TKNUM},
    {Value: TM_DPTBG},
    {Value: TM_DPTEN},
    {Value: TM_DATBG},
    {Value: TM_DATEN},
    {Value: DL_LFDAT},
    {Value: SO_EDATU_CONFIRMED},
    {Value: TM_TDLNR_NAME1},
    {Value: TM_EXTI1},
    {Value: SO_INCO1},
    {Value: SO_ROUTE},
    {Value: DL_WADAT_IST},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS}
]};

annotate service.allIssues with @UI.LineItem #nps95: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_MAKTX},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_ORT01},
    {Value: SO_LAND1},
    {Value: DL_VBELN},
    {Value: DL_POSNR},
    {Value: TM_SHIPMENT_CURRENT_STATUS},
    // {Value: TM_SHIPMENT_ALERT},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_EDATU_CONFIRMED},
    {Value: DL_LFDAT},
    {Value: TM_DPTEN},
    {Value: TM_DATEN},
    {Value: TM_TKNUM},
    {Value: TM_TDLNR_NAME1},
    {Value: SO_ROUTE}

]};

annotate service.allIssues with @UI.LineItem #nps99: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: DL_VBELN},
    {Value: DL_POSNR},
    {Value: SO_ISSUE_LOCATION},
    {Value: SO_ISSUE_LOCATION_ITEM},
    {Value: SO_FAKSP},
    {Value: SO_FAKSP_VTEXT},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_AG_PARTNER_NAME},
    {Value: DL_VGBEL},
    {Value: DL_VGPOS},
    {Value: SO_WERKS},
    {Value: SO_NETWR},
    {Value: SO_ZZDKPPRODB},
    {Value: SO_MAKTX},
    {Value: SO_ERDAT_ITEM}

]};

annotate service.allIssues with @UI.LineItem #nps00: {$value: [
    {Value: SO_VBELN},
    {Value: SO_POSNR},
    {Value: SO_DUE_DATE},
    {Value: SO_NPS},
    {Value: SO_ISSUE},
    {Value: SO_ERDAT_ITEM},
    {Value: SO_WE_PARTNER_NAME},
    {Value: SO_LAND1},
    {Value: SO_LANDX},
    {Value: SO_ORT01},
    {Value: SO_WERKS},
    {Value: SO_MAKTX},
    {Value: SO_MATNR},
    {Value: SO_KDMAT},
    {Value: SO_EDATU_REQUESTED},
    {Value: SO_EDATU_CONFIRMED},
    {Value: SO_ZZDKPPRODB},
    {Value: DL_VBELN},
    {Value: DL_POSNR},
    {Value: TM_TKNUM},
    {Value: DL_WADAT_IST},
    {Value: TM_TDLNR},
    {Value: TM_TDLNR_NAME1},
    {Value: SO_VKORG_NAME1},
    {Value: SO_VTWEG},
    {Value: SO_KWMENG},
    {Value: SO_KBMENG},
    {Value: SO_NETWR},
    {Value: SO_KBETR},
    {Value: SO_ROUTE},
    {Value: SO_F_LDDAT},
    {Value: TM_DPTBG},
    {Value: TM_DPTEN},
    {Value: TM_DATBG},
    {Value: TM_DATEN},
    {Value: TM_SHIPMENT_CURRENT_STATUS},
    {Value: TM_VISTA_STATUS}

]};

// ------------- different tabs qualifier for lineitems-------