using openOrdersSrv as service from '../../srv/order-monitoring-amoo-services.cds';

// Global fields annotations (e.g. labels and titles)
// This affects both allIssues and valueHelps entities
annotate service.baseEntity with {
    SO_VBELN                         @title: '{i18n>SO_VBELN}'                         @sap.Label: '{i18n>SO_VBELN}'              @Common.IsDigitSequence: true;
    SO_POSNR                         @title: '{i18n>SO_POSNR}'                         @sap.Label: '{i18n>SO_POSNR}'              @Common.IsDigitSequence: true;
    SO_ERDAT_ORDER                   @title: '{i18n>SO_ERDAT_ORDER}'                   @sap.Label: '{i18n>SO_ERDAT_ORDER}'        @sap.filter.restriction: 'interval';
    SO_ERDAT_ITEM                    @title: '{i18n>SO_ERDAT_ITEM}'                    @sap.Label: '{i18n>SO_ERDAT_ITEM}'         @sap.filter.restriction: 'interval';
    SO_AUART                         @title: '{i18n>SO_AUART}'                         @sap.Label: '{i18n>SO_AUART}';
    SO_WERKS                         @title: '{i18n>SO_WERKS}'                         @sap.Label: '{i18n>SO_WERKS}';
    SO_VTWEG                         @title: '{i18n>SO_VTWEG}'                         @sap.Label: '{i18n>SO_VTWEG}';
    SO_MATNR                         @title: '{i18n>SO_MATNR}'                         @sap.Label: '{i18n>SO_MATNR}'              @Common.IsDigitSequence: true;
    SO_MAKTX                         @title: '{i18n>SO_MAKTX}'                         @sap.Label: '{i18n>SO_MAKTX}';
    SO_KDMAT                         @title: '{i18n>SO_KDMAT}'                         @sap.Label: '{i18n>SO_KDMAT}';
    SO_AG_PARTNER                    @title: '{i18n>SO_AG_PARTNER}'                    @sap.Label: '{i18n>SO_AG_PARTNER}'         @Common.IsDigitSequence: true;
    SO_AG_PARTNER_NAME               @title: '{i18n>SO_AG_PARTNER_NAME}'               @sap.Label: '{i18n>SO_AG_PARTNER_NAME}';
    SO_WE_PARTNER                    @title: '{i18n>SO_WE_PARTNER}'                    @sap.Label: '{i18n>SO_WE_PARTNER}'         @Common.IsDigitSequence: true;
    SO_WE_PARTNER_NAME               @title: '{i18n>SO_WE_PARTNER_NAME}'               @sap.Label: '{i18n>SO_WE_PARTNER_NAME}';
    SO_LAND1                         @title: '{i18n>SO_LAND1}'                         @sap.Label: '{i18n>SO_LAND1}';
    SO_LANDX                         @title: '{i18n>SO_LANDX}'                         @sap.Label: '{i18n>SO_LANDX}';
    SO_ORT01                         @title: '{i18n>SO_ORT01}'                         @sap.Label: '{i18n>SO_ORT01}';
    SO_VKORG                         @title: '{i18n>SO_VKORG}'                         @sap.Label: '{i18n>SO_VKORG}';
    SO_VKORG_NAME1                   @title: '{i18n>SO_VKORG_NAME1}'                   @sap.Label: '{i18n>SO_VKORG_NAME1}';
    SO_CO_PARTNER                    @title: '{i18n>SO_CO_PARTNER}'                    @sap.Label: '{i18n>SO_CO_PARTNER}'         @Common.IsDigitSequence: true;
    SO_CO_PARTNER_NAME               @title: '{i18n>SO_CO_PARTNER_NAME}'               @sap.Label: '{i18n>SO_CO_PARTNER_NAME}';
    SO_NY_PARTNER                    @title: '{i18n>SO_NY_PARTNER}'                    @sap.Label: '{i18n>SO_NY_PARTNER}'         @Common.IsDigitSequence: true;
    SO_NY_PARTNER_NAME               @title: '{i18n>SO_NY_PARTNER_NAME}'               @sap.Label: '{i18n>SO_NY_PARTNER_NAME}';
    SO_AS_PARTNER                    @title: '{i18n>SO_AS_PARTNER}'                    @sap.Label: '{i18n>SO_AS_PARTNER}'         @Common.IsDigitSequence: true;
    SO_AS_PARTNER_NAME               @title: '{i18n>SO_AS_PARTNER_NAME}'               @sap.Label: '{i18n>SO_AS_PARTNER_NAME}';
    SO_VE_PARTNER                    @title: '{i18n>SO_VE_PARTNER}'                    @sap.Label: '{i18n>SO_VE_PARTNER}'         @Common.IsDigitSequence: true;
    SO_VE_PARTNER_NAME               @title: '{i18n>SO_VE_PARTNER_NAME}'               @sap.Label: '{i18n>SO_VE_PARTNER_NAME}';
    SO_AM_PARTNER                    @title: '{i18n>SO_AM_PARTNER}'                    @sap.Label: '{i18n>SO_AM_PARTNER}'         @Common.IsDigitSequence: true;
    SO_AM_PARTNER_NAME               @title: '{i18n>SO_AM_PARTNER_NAME}'               @sap.Label: '{i18n>SO_AM_PARTNER_NAME}';
    SO_KNREF_HEAD                    @title: '{i18n>SO_KNREF_HEAD}'                    @sap.Label: '{i18n>SO_KNREF_HEAD}';
    SO_VBUND                         @title: '{i18n>SO_VBUND}'                         @sap.Label: '{i18n>SO_VBUND}';
    SO_EDATU_REQUESTED               @title: '{i18n>SO_EDATU_REQUESTED}'               @sap.Label: '{i18n>SO_EDATU_REQUESTED}'    @sap.filter.restriction: 'interval';
    SO_KWMENG                        @title: '{i18n>SO_KWMENG}'                        @sap.Label: '{i18n>SO_KWMENG}';
    SO_VRKME                         @title: '{i18n>SO_VRKME}'                         @sap.Label: '{i18n>SO_VRKME}';
    SO_EDATU_CONFIRMED               @title: '{i18n>SO_EDATU_CONFIRMED}'               @sap.Label: '{i18n>SO_EDATU_CONFIRMED}'    @sap.filter.restriction: 'interval';
    SO_KBMENG                        @title: '{i18n>SO_KBMENG}'                        @sap.Label: '{i18n>SO_KBMENG}';
    SO_UNCONFIRMED_QTY               @title: '{i18n>SO_UNCONFIRMED_QTY}'               @sap.Label: '{i18n>SO_UNCONFIRMED_QTY}';
    SO_REQ_TEXT                      @title: '{i18n>SO_REQ_TEXT}'                      @sap.Label: '{i18n>SO_REQ_TEXT}';
    SO_FAKSP                         @title: '{i18n>SO_FAKSP}'                         @sap.Label: '{i18n>SO_FAKSP}';
    SO_FAKSP_VTEXT                   @title: '{i18n>SO_FAKSP_VTEXT}'                   @sap.Label: '{i18n>SO_FAKSP_VTEXT}';
    SO_SUPPLY_SITUATION              @title: '{i18n>SO_SUPPLY_SITUATION}'              @sap.Label: '{i18n>SO_SUPPLY_SITUATION}';
    SO_SUPPLY_SITUATION_DESCR        @title: '{i18n>SO_SUPPLY_SITUATION_DESCR}'        @sap.Label: '{i18n>SO_SUPPLY_SITUATION_DESCR}';
    SO_KBETR                         @title: '{i18n>SO_KBETR}'                         @sap.Label: '{i18n>SO_KBETR}';
    SO_WAERS                         @title: '{i18n>SO_WAERS}'                         @sap.Label: '{i18n>SO_WAERS}';
    SO_KPEIN                         @title: '{i18n>SO_KPEIN}'                         @sap.Label: '{i18n>SO_KPEIN}';
    SO_KMEIN                         @title: '{i18n>SO_KMEIN}'                         @sap.Label: '{i18n>SO_KMEIN}';
    SO_NETWR                         @title: '{i18n>SO_NETWR}'                         @sap.Label: '{i18n>SO_NETWR}';
    SO_WAERK                         @title: '{i18n>SO_WAERK}'                         @sap.Label: '{i18n>SO_WAERK}';
    SO_HTEXT                         @title: '{i18n>SO_HTEXT}'                         @sap.Label: '{i18n>SO_HTEXT}';
    SO_PSTYV                         @title: '{i18n>SO_PSTYV}'                         @sap.Label: '{i18n>SO_PSTYV}';
    SO_PSTYV_VTEXT                   @title: '{i18n>SO_PSTYV_VTEXT}'                   @sap.Label: '{i18n>SO_PSTYV_VTEXT}';
    SO_DISPO                         @title: '{i18n>SO_DISPO}'                         @sap.Label: '{i18n>SO_DISPO}';
    SO_KOSCH                         @title: '{i18n>SO_KOSCH}'                         @sap.Label: '{i18n>SO_KOSCH}';
    SO_VKBUR                         @title: '{i18n>SO_VKBUR}'                         @sap.Label: '{i18n>SO_VKBUR}';
    SO_VKBUR_BEZEI                   @title: '{i18n>SO_VKBUR_BEZEI}'                   @sap.Label: '{i18n>SO_VKBUR_BEZEI}';
    SO_ABGRU                         @title: '{i18n>SO_ABGRU}'                         @sap.Label: '{i18n>SO_ABGRU}';
    SO_ABGRU_BEZEI                   @title: '{i18n>SO_ABGRU_BEZEI}'                   @sap.Label: '{i18n>SO_ABGRU_BEZEI}';
    SO_ABSTA                         @title: '{i18n>SO_ABSTA}'                         @sap.Label: '{i18n>SO_ABSTA}';
    SO_KNUMV                         @title: '{i18n>SO_KNUMV}'                         @sap.Label: '{i18n>SO_KNUMV}';
    SO_SPART                         @title: '{i18n>SO_SPART}'                         @sap.Label: '{i18n>SO_SPART}';
    SO_INCO1                         @title: '{i18n>SO_INCO1}'                         @sap.Label: '{i18n>SO_INCO1}';
    SO_INCO2                         @title: '{i18n>SO_INCO2}'                         @sap.Label: '{i18n>SO_INCO2}';
    SO_ZTERM                         @title: '{i18n>SO_ZTERM}'                         @sap.Label: '{i18n>SO_ZTERM}';
    SO_PRSDT                         @title: '{i18n>SO_PRSDT}'                         @sap.Label: '{i18n>SO_PRSDT}';
    SO_ZZ0S2REVG2                    @title: '{i18n>SO_ZZ0S2REVG2}'                    @sap.Label: '{i18n>SO_ZZ0S2REVG2}';
    SO_ZZDKPPRODB                    @title: '{i18n>SO_ZZDKPPRODB}'                    @sap.Label: '{i18n>SO_ZZDKPPRODB}';
    SO_BSARK                         @title: '{i18n>SO_BSARK}'                         @sap.Label: '{i18n>SO_BSARK}';
    SO_BSARK_VTEXT                   @title: '{i18n>SO_BSARK_VTEXT}'                   @sap.Label: '{i18n>SO_BSARK_VTEXT}';
    SO_BASF_LOFCR                    @title: '{i18n>SO_BASF_LOFCR}'                    @sap.Label: '{i18n>SO_BASF_LOFCR}';
    SO_GUSCON_LEVEL                  @title: '{i18n>SO_GUSCON_LEVEL}'                  @sap.Label: '{i18n>SO_GUSCON_LEVEL}';
    SO_I_VBELN                       @title: '{i18n>SO_I_VBELN}'                       @sap.Label: '{i18n>SO_I_VBELN}'            @Common.IsDigitSequence: true;
    SO_LEVEL_TYPE                    @title: '{i18n>SO_LEVEL_TYPE}'                    @sap.Label: '{i18n>SO_LEVEL_TYPE}'         @Common.IsDigitSequence: true;
    SO_N_VBELN                       @title: '{i18n>SO_N_VBELN}'                       @sap.Label: '{i18n>SO_N_VBELN}'            @Common.IsDigitSequence: true;
    SO_F_VBELN                       @title: '{i18n>SO_F_VBELN}'                       @sap.Label: '{i18n>SO_F_VBELN}'            @Common.IsDigitSequence: true;
    SO_F_POSNR                       @title: '{i18n>SO_F_POSNR}'                       @sap.Label: '{i18n>SO_F_POSNR}'            @Common.IsDigitSequence: true;
    SO_VBTYP                         @title: '{i18n>SO_VBTYP}'                         @sap.Label: '{i18n>SO_VBTYP}';
    SO_BSTKD                         @title: '{i18n>SO_BSTKD}'                         @sap.Label: '{i18n>SO_BSTKD}';
    SO_TRAGR                         @title: '{i18n>SO_TRAGR}'                         @sap.Label: '{i18n>SO_TRAGR}'              @Common.IsDigitSequence: true;
    SO_TRAGR_VTEXT                   @title: '{i18n>SO_TRAGR_VTEXT}'                   @sap.Label: '{i18n>SO_TRAGR_VTEXT}';
    SO_VKGRP                         @title: '{i18n>SO_VKGRP}'                         @sap.Label: '{i18n>SO_VKGRP}';
    SO_VKGRP_BEZEI                   @title: '{i18n>SO_VKGRP_BEZEI}'                   @sap.Label: '{i18n>SO_VKGRP_BEZEI}';
    SO_ROUTE                         @title: '{i18n>SO_ROUTE}'                         @sap.Label: '{i18n>SO_ROUTE}';
    SO_F_WERKS                       @title: '{i18n>SO_F_WERKS}'                       @sap.Label: '{i18n>SO_F_WERKS}';
    SO_F_VKORG                       @title: '{i18n>SO_F_VKORG}'                       @sap.Label: '{i18n>SO_F_VKORG}';
    SO_F_VKORG_VTEXT                 @title: '{i18n>SO_F_VKORG_VTEXT}'                 @sap.Label: '{i18n>SO_F_VKORG_VTEXT}';
    SO_F_AS_PARTNER                  @title: '{i18n>SO_F_AS_PARTNER}'                  @sap.Label: '{i18n>SO_F_AS_PARTNER}'       @Common.IsDigitSequence: true;
    SO_F_AS_PARTNER_NAME             @title: '{i18n>SO_F_AS_PARTNER_NAME}'             @sap.Label: '{i18n>SO_F_AS_PARTNER_NAME}';
    SO_F_LDDAT                       @title: '{i18n>SO_F_LDDAT}'                       @sap.Label: '{i18n>SO_F_LDDAT}'            @sap.filter.restriction: 'interval';
    SO_F_LGORT                       @title: '{i18n>SO_LGORT}'                         @sap.Label: '{i18n>SO_LGORT}';
    SO_F_TDDAT                       @title: '{i18n>SO_F_TDDAT}'                       @sap.Label: '{i18n>SO_F_TDDAT}'            @sap.filter.restriction: 'interval';
    SO_F_ZZ0S2MATUG                  @title: '{i18n>SO_F_ZZ0S2MATUG}'                  @sap.Label: '{i18n>SO_F_ZZ0S2MATUG}';
    SO_F_AUFNR                       @title: '{i18n>SO_F_AUFNR}'                       @sap.Label: '{i18n>SO_F_AUFNR}';
    SO_F_DGLTP                       @title: '{i18n>SO_F_DGLTP}'                       @sap.Label: '{i18n>SO_F_DGLTP}'            @sap.filter.restriction: 'interval';
    SO_F_AMEIN                       @title: '{i18n>SO_F_AMEIN}'                       @sap.Label: '{i18n>SO_F_AMEIN}';
    SO_F_PSMNG                       @title: '{i18n>SO_F_PSMNG}'                       @sap.Label: '{i18n>SO_F_PSMNG}';
    SO_F_VSBED                       @title: '{i18n>SO_F_VSBED}'                       @sap.Label: '{i18n>SO_F_VSBED}';
    SO_F_VSBED_VTEXT                 @title: '{i18n>SO_F_VSBED_VTEXT}'                 @sap.Label: '{i18n>SO_F_VSBED_VTEXT}';
    LAST_NOTE                        @title: '{i18n>LAST_NOTE}'                        @sap.Label: '{i18n>LAST_NOTE}';
    DL_VBELN                         @title: '{i18n>DL_VBELN}'                         @sap.Label: '{i18n>DL_VBELN}';             
    DL_POSNR                         @title: '{i18n>DL_POSNR}'                         @sap.Label: '{i18n>DL_POSNR}'              @Common.IsDigitSequence: true;
    DL_CHARG                         @title: '{i18n>DL_CHARG}'                         @sap.Label: '{i18n>DL_CHARG}';
    DL_LFDAT                         @title: '{i18n>DL_LFDAT}'                         @sap.Label: '{i18n>DL_LFDAT}'              @sap.filter.restriction: 'interval';
    DL_HSDAT                         @title: '{i18n>DL_HSDAT}'                         @sap.Label: '{i18n>DL_HSDAT}'              @sap.filter.restriction: 'interval';
    DL_VFDAT                         @title: '{i18n>DL_VFDAT}'                         @sap.Label: '{i18n>DL_VFDAT}'              @sap.filter.restriction: 'interval';
    DL_LFIMG                         @title: '{i18n>DL_LFIMG}'                         @sap.Label: '{i18n>DL_LFIMG}';
    DL_VRKME                         @title: '{i18n>DL_VRKME}'                         @sap.Label: '{i18n>DL_VRKME}';
    DL_POSAR                         @title: '{i18n>DL_POSAR}'                         @sap.Label: '{i18n>DL_POSAR}';
    DL_VGBEL                         @title: '{i18n>DL_VGBEL}'                         @sap.Label: '{i18n>DL_VGBEL}';
    DL_VGPOS                         @title: '{i18n>DL_VGPOS}'                         @sap.Label: '{i18n>DL_VGPOS}'              @Common.IsDigitSequence: true;
    DL_LFART                         @title: '{i18n>DL_LFART}'                         @sap.Label: '{i18n>DL_LFART}';
    DL_LFART_VTEXT                   @title: '{i18n>DL_LFART_VTEXT}'                   @sap.Label: '{i18n>DL_LFART_VTEXT}';
    DL_TRAID                         @title: '{i18n>DL_TRAID}'                         @sap.Label: '{i18n>DL_TRAID}';
    DL_ZZ0S2BLNR                     @title: '{i18n>DL_ZZ0S2BLNR}'                     @sap.Label: '{i18n>DL_ZZ0S2BLNR}';
    DL_PEND_DEL_QUAN                 @title: '{i18n>DL_PEND_DEL_QUAN}'                 @sap.Label: '{i18n>DL_PEND_DEL_QUAN}';
    DL_WADAT                         @title: '{i18n>DL_WADAT}'                         @sap.Label: '{i18n>DL_WADAT}'              @sap.filter.restriction: 'interval';
    DL_WADAT_IST                     @title: '{i18n>DL_WADAT_IST}'                     @sap.Label: '{i18n>DL_WADAT_IST}'          @sap.filter.restriction: 'interval';
    TM_TKNUM                         @title: '{i18n>TM_TKNUM}'                         @sap.Label: '{i18n>TM_TKNUM}';
    TM_VSART                         @title: '{i18n>TM_VSART}'                         @sap.Label: '{i18n>TM_VSART}';
    TM_VSART_BEZEI                   @title: '{i18n>TM_VSART_BEZEI}'                   @sap.Label: '{i18n>TM_VSART_BEZEI}';
    TM_EXTI1                         @title: '{i18n>TM_EXTI1}'                         @sap.Label: '{i18n>TM_EXTI1}';
    TM_DPTBG                         @title: '{i18n>TM_DPTBG}'                         @sap.Label: '{i18n>TM_DPTBG}'              @sap.filter.restriction: 'interval';
    TM_DATBG                         @title: '{i18n>TM_DATBG}'                         @sap.Label: '{i18n>TM_DATBG}'              @sap.filter.restriction: 'interval';
    TM_DPTEN                         @title: '{i18n>TM_DPTEN}'                         @sap.Label: '{i18n>TM_DPTEN}'              @sap.filter.restriction: 'interval';
    TM_DALBG                         @title: '{i18n>TM_DALBG}'                         @sap.Label: '{i18n>TM_DALBG}'              @sap.filter.restriction: 'interval';
    TM_DATEN                         @title: '{i18n>TM_DATEN}'                         @sap.Label: '{i18n>TM_DATEN}'              @sap.filter.restriction: 'interval';
    TM_AR_DATE                       @title: '{i18n>TM_AR_DATE}'                       @sap.Label: '{i18n>TM_AR_DATE}'            @sap.filter.restriction: 'interval';
    TM_TDLNR                         @title: '{i18n>TM_TDLNR}'                         @sap.Label: '{i18n>TM_TDLNR}'              @Common.IsDigitSequence: true;
    TM_TDLNR_NAME1                   @title: '{i18n>TM_TDLNR_NAME1}'                   @sap.Label: '{i18n>TM_TDLNR_NAME1}';
    TM_TRACKING_ID_COMP              @title: '{i18n>TM_TRACKING_ID_COMP}'              @sap.Label: '{i18n>TM_TRACKING_ID_COMP}';
    TM_TRACKING_ID_ELEM              @title: '{i18n>TM_TRACKING_ID_ELEM}'              @sap.Label: '{i18n>TM_TRACKING_ID_ELEM}';
    TM_STTRG                         @title: '{i18n>TM_STTRG}'                         @sap.Label: '{i18n>TM_STTRG}';
    TM_STTRG_DDTEXT                  @title: '{i18n>TM_STTRG_DDTEXT}'                  @sap.Label: '{i18n>TM_STTRG_DDTEXT}';
    TM_SHIPMENT_CURRENT_STATUS       @title: '{i18n>TM_SHIPMENT_CURRENT_STATUS}'       @sap.Label: '{i18n>TM_SHIPMENT_CURRENT_STATUS}';
    SO_NPS                           @title: '{i18n>SO_NPS}'                           @sap.Label: '{i18n>SO_NPS}';
    SO_NPS_DESCRIPTION               @title: '{i18n>SO_NPS}'                           @sap.Label: '{i18n>SO_NPS}';
    SO_ISSUE                         @title: '{i18n>SO_ISSUE}'                         @sap.Label: '{i18n>SO_ISSUE}';
    SO_ISSUE_DESCRIPTION             @title: '{i18n>SO_ISSUE}'                         @sap.Label: '{i18n>SO_ISSUE}';
    SO_DCP_ITEM_STATUS               @title: '{i18n>SO_DCP_ITEM_STATUS}'               @sap.Label: '{i18n>SO_DCP_ITEM_STATUS}';
    SO_DCP_ITEM_STATUS_DESCRIPTION   @title: '{i18n>SO_DCP_ITEM_STATUS}'               @sap.Label: '{i18n>SO_DCP_ITEM_STATUS}';
    SO_DUE_DATE                      @title: '{i18n>SO_DUE_DATE}'                      @sap.Label: '{i18n>SO_DUE_DATE}'           @sap.filter.restriction: 'interval';
    SO_ISSUE_LOCATION                @title: '{i18n>SO_ISSUE_LOCATION}'                @sap.Label: '{i18n>SO_ISSUE_LOCATION}';
    SO_ISSUE_LOCATION_ITEM           @title: '{i18n>SO_ISSUE_LOCATION_ITEM}'           @sap.Label: '{i18n>SO_ISSUE_LOCATION_ITEM}';
    DL_ISSUE_ROOT                    @title: '{i18n>DL_ISSUE_ROOT}'                    @sap.Label: '{i18n>DL_ISSUE_ROOT}';
    DL_ISSUE_ROOT_ITEM               @title: '{i18n>DL_ISSUE_ROOT_ITEM}'               @sap.Label: '{i18n>DL_ISSUE_ROOT_ITEM}'    @Common.IsDigitSequence: true;
    criticalityDueDate               @title: '{i18n>dueDateCriticality}'               @sap.Label: '{i18n>dueDateCriticality}';
    BL_VBELN_INV_FIRST               @title: '{i18n>BL_VBELN_INV_FIRST}'               @sap.Label: '{i18n>BL_VBELN_INV_FIRST}'    @Common.IsDigitSequence: true;
    BL_POSNR_INV_FIRST               @title: '{i18n>BL_POSNR_INV_FIRST}'               @sap.Label: '{i18n>BL_POSNR_INV_FIRST}'    @Common.IsDigitSequence: true;
    BL_FKIMG_FIRST                   @title: '{i18n>BL_FKIMG_FIRST}'                   @sap.Label: '{i18n>BL_FKIMG_FIRST}';
    BL_VRKME_FIRST                   @title: '{i18n>BL_VRKME_FIRST}'                   @sap.Label: '{i18n>BL_VRKME_FIRST}';
    BL_FKART_FIRST                   @title: '{i18n>BL_FKART_FIRST}'                   @sap.Label: '{i18n>BL_FKART_FIRST}';
    BL_VBELN_INV_LAST                @title: '{i18n>BL_VBELN_INV_LAST}'                @sap.Label: '{i18n>BL_VBELN_INV_LAST}'     @Common.IsDigitSequence: true;
    BL_POSNR_INV_LAST                @title: '{i18n>BL_POSNR_INV_LAST}'                @sap.Label: '{i18n>BL_POSNR_INV_LAST}'     @Common.IsDigitSequence: true;
    BL_FKIMG_LAST                    @title: '{i18n>BL_FKIMG_LAST}'                    @sap.Label: '{i18n>BL_FKIMG_LAST}';
    BL_FKART_LAST                    @title: '{i18n>BL_FKART_LAST}'                    @sap.Label: '{i18n>BL_FKART_LAST}';
    BL_VRKME_LAST                    @title: '{i18n>BL_VRKME_LAST}'                    @sap.Label: '{i18n>BL_VRKME_LAST}';
    BL_XBLNR                         @title: '{i18n>BL_XBLNR}'                         @sap.Label: '{i18n>BL_XBLNR}';
    BL_NETWR_LAST                    @title: '{i18n>BL_NETWR_LAST}'                    @sap.Label: '{i18n>BL_NETWR_LAST}';
    BL_ERDAT_FIRST                   @title: '{i18n>BL_ERDAT_FIRST}'                   @sap.Label: '{i18n>BL_ERDAT_FIRST}';
    BL_ERDAT_LAST                    @title: '{i18n>BL_ERDAT_LAST}'                    @sap.Label: '{i18n>BL_ERDAT_LAST}';
    BL_WAERK_LAST                    @title: '{i18n>BL_WAERK_LAST}'                    @sap.Label: '{i18n>BL_WAERK_LAST}';
    SO_FOLLOWUP_NOTES_LANG           @title: '{i18n>SO_FOLLOWUP_NOTES_LANG}'           @sap.Label: '{i18n>SO_FOLLOWUP_NOTES_LANG}';
    SO_REASON_CODE_01_LANG           @title: '{i18n>SO_REASON_CODE_01_LANG}'           @sap.Label: '{i18n>SO_REASON_CODE_01_LANG}';
    SO_REASON_CODE_02_LANG           @title: '{i18n>SO_REASON_CODE_02_LANG}'           @sap.Label: '{i18n>SO_REASON_CODE_02_LANG}';
    SO_REASON_CODE_03_LANG           @title: '{i18n>SO_REASON_CODE_03_LANG}'           @sap.Label: '{i18n>SO_REASON_CODE_03_LANG}';
    SO_REASON_CODE_04_LANG           @title: '{i18n>SO_REASON_CODE_04_LANG}'           @sap.Label: '{i18n>SO_REASON_CODE_04_LANG}';
    SO_REASON_CODE_05_LANG           @title: '{i18n>SO_REASON_CODE_05_LANG}'           @sap.Label: '{i18n>SO_REASON_CODE_05_LANG}';
    SO_DEV_CONF_DATE                 @title: '{i18n>SO_DEV_CONF_DATE}'                 @sap.Label: '{i18n>SO_DEV_CONF_DATE}';
    SO_EMAIL                         @title: '{i18n>SO_EMAIL}'                         @sap.Label: '{i18n>SO_EMAIL}';
    SO_EMAIL_SEND_DATE_F             @title: '{i18n>SO_EMAIL_SEND_DATE_F}'             @sap.Label: '{i18n>SO_EMAIL_SEND_DATE_F}';
    SO_EMAIL_SENT_ON                 @title: '{i18n>SO_EMAIL_SENT_ON}'                 @sap.Label: '{i18n>SO_EMAIL_SENT_ON}';
    SO_MDB                           @title: '{i18n>SO_MDB}'                           @sap.Label: '{i18n>SO_MDB}';
    SO_MDB_TEXT                      @title: '{i18n>SO_MDB_TEXT}'                      @sap.Label: '{i18n>SO_MDB_TEXT}';
    DL_ERDAT                         @title: '{i18n>DL_ERDAT}'                         @sap.Label: '{i18n>DL_ERDAT}'              @sap.filter.restriction: 'interval';
    DL_LDDAT                         @title: '{i18n>DL_LDDAT}'                         @sap.Label: '{i18n>DL_LDDAT}'              @sap.filter.restriction: 'interval';
    SO_PERFK                         @title: '{i18n>SO_PERFK}'                         @sap.Label: '{i18n>SO_PERFK}';
    SO_PERFK_LTEXT_LANG              @title: '{i18n>SO_PERFK}'                         @sap.Label: '{i18n>SO_PERFK}';
    SO_F_MBDAT                       @title: '{i18n>SO_F_MBDAT}'                       @sap.Label: '{i18n>SO_F_MBDAT}'            @sap.filter.restriction: 'interval';
    DL_POSNR_BATCH                   @title: '{i18n>DL_POSNR_BATCH}'                   @sap.Label: '{i18n>DL_POSNR_BATCH}';
    DL_LFIMG_BATCH                   @title: '{i18n>DL_LFIMG_BATCH}'                   @sap.Label: '{i18n>DL_LFIMG_BATCH}';
    PO_EBELN                         @title: '{i18n>PO_EBELN}'                         @sap.Label: '{i18n>PO_EBELN}'              @Common.IsDigitSequence: true;
    PO_EBELP                         @title: '{i18n>PO_EBELP}'                         @sap.Label: '{i18n>PO_EBELP}'              @Common.IsDigitSequence: true;
    PO_AEDAT_HEAD                    @title: '{i18n>PO_AEDAT_HEAD}'                    @sap.Label: '{i18n>PO_AEDAT_HEAD}';
    PO_AEDAT_ITEM                    @title: '{i18n>PO_AEDAT_ITEM}'                    @sap.Label: '{i18n>PO_AEDAT_ITEM}';
    PO_BSART                         @title: '{i18n>PO_BSART}'                         @sap.Label: '{i18n>PO_BSART}';
    PO_BSART_BATXT                   @title: '{i18n>PO_BSART_BATXT}'                   @sap.Label: '{i18n>PO_BSART_BATXT}';
    PO_EKORG                         @title: '{i18n>PO_EKORG}'                         @sap.Label: '{i18n>PO_EKORG}';
    PO_EKOTX                         @title: '{i18n>PO_EKOTX}'                         @sap.Label: '{i18n>PO_EKOTX}';
    PO_EKGRP                         @title: '{i18n>PO_EKGRP}'                         @sap.Label: '{i18n>PO_EKGRP}';
    PO_EKNAM                         @title: '{i18n>PO_EKNAM}'                         @sap.Label: '{i18n>PO_EKNAM}';
    PO_EMATN                         @title: '{i18n>PO_EMATN}'                         @sap.Label: '{i18n>PO_EMATN}';
    PO_WERKS_PO                      @title: '{i18n>PO_WERKS_PO}'                      @sap.Label: '{i18n>PO_WERKS_PO}';
    PO_MENGE                         @title: '{i18n>PO_MENGE}'                         @sap.Label: '{i18n>PO_MENGE}';
    PO_MEINS                         @title: '{i18n>PO_MEINS}'                         @sap.Label: '{i18n>PO_MEINS}';
    PO_KUNNR                         @title: '{i18n>PO_KUNNR}'                         @sap.Label: '{i18n>PO_KUNNR}';
    PO_KUNNR_NAME                    @title: '{i18n>PO_KUNNR_NAME}'                    @sap.Label: '{i18n>PO_KUNNR_NAME}';
    PO_PARTNER_9A_HEAD               @title: '{i18n>PO_PARTNER_9A_HEAD}'               @sap.Label: '{i18n>PO_PARTNER_9A_HEAD}';
    PO_PARTNER_9O_HEAD               @title: '{i18n>PO_PARTNER_9O_HEAD}'               @sap.Label: '{i18n>PO_PARTNER_9O_HEAD}';
    SO_Z5_PARTNER                    @title: '{i18n>SO_Z5_PARTNER}'                    @sap.Label: '{i18n>SO_Z5_PARTNER}'         @Common.IsDigitSequence: true;
    SO_Z5_PARTNER_NAME               @title: '{i18n>SO_Z5_PARTNER_NAME}'               @sap.Label: '{i18n>SO_Z5_PARTNER_NAME}';
    SO_SB_PARTNER                    @title: '{i18n>SO_SB_PARTNER}'                    @sap.Label: '{i18n>SO_SB_PARTNER}'         @Common.IsDigitSequence: true;
    SO_SB_PARTNER_NAME               @title: '{i18n>SO_SB_PARTNER_NAME}'               @sap.Label: '{i18n>SO_SB_PARTNER_NAME}';
    SO_AD_PARTNER                    @title: '{i18n>SO_AD_PARTNER}'                    @sap.Label: '{i18n>SO_AD_PARTNER}'         @Common.IsDigitSequence: true;
    SO_AD_PARTNER_NAME               @title: '{i18n>SO_AD_PARTNER_NAME}'               @sap.Label: '{i18n>SO_AD_PARTNER_NAME}';
    SO_MANDT                         @title: '{i18n>SO_MANDT}'                         @sap.Label: '{i18n>SO_MANDT}';
    DL_MANDT                         @title: '{i18n>DL_MANDT}'                         @sap.Label: '{i18n>DL_MANDT}';
    TM_MANDT                         @title: '{i18n>TM_MANDT}'                         @sap.Label: '{i18n>TM_MANDT}';
    BL_MANDT_INV_FIRST               @title: '{i18n>BL_MANDT_INV_FIRST}'               @sap.Label: '{i18n>BL_MANDT_INV_FIRST}';
    BL_MANDT_INV_LAST                @title: '{i18n>BL_MANDT_INV_LAST}'                @sap.Label: '{i18n>BL_MANDT_INV_LAST}';
    SO_FIRST_SO_MANDT                @title: '{i18n>SO_FIRST_SO_MANDT}'                @sap.Label: '{i18n>SO_FIRST_SO_MANDT}';
    SO_FINAL_SO_MANDT                @title: '{i18n>SO_FINAL_SO_MANDT}'                @sap.Label: '{i18n>SO_FINAL_SO_MANDT}';
    PO_MANDT                         @title: '{i18n>PO_MANDT}'                         @sap.Label: '{i18n>PO_MANDT}';
    SO_ISSUE_LOCATION_MANDT          @title: '{i18n>SO_ISSUE_LOCATION_MANDT}'          @sap.Label: '{i18n>SO_ISSUE_LOCATION_MANDT}';
    SO_MANDT_TEXT                    @title: '{i18n>SO_MANDT}'                         @sap.Label: '{i18n>SO_MANDT}';
    DL_MANDT_TEXT                    @title: '{i18n>DL_MANDT}'                         @sap.Label: '{i18n>DL_MANDT}';
    TM_MANDT_TEXT                    @title: '{i18n>TM_MANDT}'                         @sap.Label: '{i18n>TM_MANDT}';
    BL_MANDT_INV_FIRST_TEXT          @title: '{i18n>BL_MANDT_INV_FIRST}'               @sap.Label: '{i18n>BL_MANDT_INV_FIRST}';
    BL_MANDT_INV_LAST_TEXT           @title: '{i18n>BL_MANDT_INV_LAST}'                @sap.Label: '{i18n>BL_MANDT_INV_LAST}';
    SO_FIRST_SO_MANDT_TEXT           @title: '{i18n>SO_FIRST_SO_MANDT}'                @sap.Label: '{i18n>SO_FIRST_SO_MANDT}';
    SO_FINAL_SO_MANDT_TEXT           @title: '{i18n>SO_FINAL_SO_MANDT}'                @sap.Label: '{i18n>SO_FINAL_SO_MANDT}';
    PO_MANDT_TEXT                    @title: '{i18n>PO_MANDT}'                         @sap.Label: '{i18n>PO_MANDT}';
    SO_ISSUE_LOCATION_MANDT_TEXT     @title: '{i18n>SO_ISSUE_LOCATION_MANDT}'          @sap.Label: '{i18n>SO_ISSUE_LOCATION_MANDT}';
    DL_TRMTYP                        @title: '{i18n>DL_TRMTYP}'                        @sap.Label: '{i18n>DL_TRMTYP}'             @Common.IsDigitSequence: true;
    DL_TRMTYP_MAKTX                  @title: '{i18n>DL_TRMTYP_MAKTX_LANG}'             @sap.Label: '{i18n>DL_TRMTYP_MAKTX_LANG}';
    DL_ZZ0S2ABGH                     @title: '{i18n>DL_ZZ0S2ABGH}'                     @sap.Label: '{i18n>DL_ZZ0S2ABGH}';
    DL_ZZ0S2ZIEH                     @title: '{i18n>DL_ZZ0S2ZIEH}'                     @sap.Label: '{i18n>DL_ZZ0S2ZIEH}';
    TM_VISTA_STATUS                  @title: '{i18n>TM_VISTA_STATUS}'                  @sap.Label: '{i18n>TM_VISTA_STATUS}';
    TM_CURRENT_ETA_VISTA             @title: '{i18n>TM_CURRENT_ETA_VISTA}'             @sap.Label: '{i18n>TM_CURRENT_ETA_VISTA}'  @sap.filter.restriction: 'interval';
    SO_BNAME                         @title: '{i18n>SO_BNAME}'                         @sap.Label: '{i18n>SO_BNAME}';
    SO_IHREZ                         @title: '{i18n>SO_IHREZ}'                         @sap.Label: '{i18n>SO_IHREZ}';
    SO_LPRIO                         @title: '{i18n>SO_LPRIO}'                         @sap.Label: '{i18n>SO_LPRIO}';
    SO_AUGRU                         @title: '{i18n>SO_AUGRU}'                         @sap.Label: '{i18n>SO_AUGRU}';
    SO_AUGRU_BEZEI_LANG              @title: '{i18n>SO_AUGRU_BEZEI_LANG}'              @sap.Label: '{i18n>SO_AUGRU_BEZEI_LANG}';
    SO_KDGRP                         @title: '{i18n>SO_KDGRP}'                         @sap.Label: '{i18n>SO_KDGRP}';
    SO_KDGRP_KTEXT_LANG              @title: '{i18n>SO_KDGRP_KTEXT_LANG}'              @sap.Label: '{i18n>SO_KDGRP_KTEXT_LANG}';
    SO_WE_PARTNER_REGION             @title: '{i18n>SO_WE_PARTNER_REGION}'             @sap.Label: '{i18n>SO_WE_PARTNER_REGION}';
    SO_WE_PARTNER_REGION_BEZEI_LANG  @title: '{i18n>SO_WE_PARTNER_REGION_BEZEI_LANG}'  @sap.Label: '{i18n>SO_WE_PARTNER_REGION_BEZEI_LANG}';
    SO_PRCTR                         @title: '{i18n>SO_PRCTR}'                         @sap.Label: '{i18n>SO_PRCTR}';
    SO_TO_PARTNER                    @title: '{i18n>SO_TO_PARTNER}'                    @sap.Label: '{i18n>SO_TO_PARTNER}'         @Common.IsDigitSequence: true;
    SO_TO_PARTNER_NAME               @title: '{i18n>SO_TO_PARTNER_NAME}'               @sap.Label: '{i18n>SO_TO_PARTNER_NAME}';
    TM_DPLBG_DATE                    @title: '{i18n>TM_DPLBG}'                         @sap.Label: '{i18n>TM_DPLBG}';
    TM_ERDAT_DATE                    @title: '{i18n>TM_ERDAT}'                         @sap.Label: '{i18n>TM_ERDAT}';
    TM_DPREG_DATE                    @title: '{i18n>TM_DPREG}'                         @sap.Label: '{i18n>TM_DPREG}';
    DL_WERKS_DEL                     @title: '{i18n>DL_WERKS_DEL}'                     @sap.Label: '{i18n>DL_WERKS_DEL}';
    DL_VKORG_DEL                     @title: '{i18n>DL_VKORG_DEL}'                     @sap.Label: '{i18n>DL_VKORG_DEL}';
    SO_VMSTA                         @title: '{i18n>SO_VMSTA}'                         @sap.Label: '{i18n>SO_VMSTA}';
    SO_ZZ0S2VGANN                    @title: '{i18n>SO_ZZ0S2VGANN}'                    @sap.Label: '{i18n>SO_ZZ0S2VGANN}';
    SO_ZZ0S2LOANN                    @title: '{i18n>SO_ZZ0S2LOANN}'                    @sap.Label: '{i18n>SO_ZZ0S2LOANN}';
    PO_REQ_DEL_DATE                  @title: '{i18n>PO_REQ_DEL_DATE}'                  @sap.Label: '{i18n>PO_REQ_DEL_DATE}';
    PO_AB_CONF_DATE                  @title: '{i18n>PO_AB_CONF_DATE}'                  @sap.Label: '{i18n>PO_AB_CONF_DATE}';
    PO_LA_CONF_DATE                  @title: '{i18n>PO_LA_CONF_DATE}'                  @sap.Label: '{i18n>PO_LA_CONF_DATE}';
    PO_ZD_CONF_DATE                  @title: '{i18n>PO_ZD_CONF_DATE}'                  @sap.Label: '{i18n>PO_ZD_CONF_DATE}';
    SO_ZZATP_CUST                    @title: '{i18n>SO_ZZATP_CUST}'                    @sap.Label: '{i18n>SO_ZZATP_CUST}';
    SO_CONTRACT                      @title: '{i18n>SO_CONTRACT}'                      @sap.Label: '{i18n>SO_CONTRACT}';
    SO_CONTRACT_ITEM                 @title: '{i18n>SO_CONTRACT_ITEM}'                 @sap.Label: '{i18n>SO_CONTRACT_ITEM}';
    SO_ZZMHDRZ                       @title: '{i18n>SO_ZZMHDRZ}'                       @sap.Label: '{i18n>SO_ZZMHDRZ}';
    SO_ZTERM_VTEXT_LANG              @title: '{i18n>SO_ZTERM_VTEXT_LANG}'              @sap.Label: '{i18n>SO_ZTERM_VTEXT_LANG}';
    DL_SEED_COUNT                    @title: '{i18n>DL_SEED_COUNT}'                    @sap.Label: '{i18n>DL_SEED_COUNT}';
    DL_SEEDS_TAGGED_GERM             @title: '{i18n>DL_SEEDS_TAGGED_GERM}'             @sap.Label: '{i18n>DL_SEEDS_TAGGED_GERM}';
    BL_XREF3                         @title: '{i18n>BL_XREF3}'                         @sap.Label: '{i18n>BL_XREF3}';
    @Common.Text           : SO_DGSTA_DDTEXT_LANG
    @Common.TextArrangement: #TextFirst
    SO_DGSTA                         @title: '{i18n>SO_DGSTA}'                         @sap.Label: '{i18n>SO_DGSTA}';
    @Common.TextFor
    SO_DGSTA_DDTEXT_LANG             @title: '{i18n>SO_DGSTA_DDTEXT_LANG}'             @sap.Label: '{i18n>SO_DGSTA_DDTEXT_LANG}';
    @Common.Text           : SO_MVGR2_BEZEI_LANG
    @Common.TextArrangement: #TextFirst
    SO_MVGR2                         @title: '{i18n>SO_MVGR2}'                         @sap.Label: '{i18n>SO_MVGR2}';
    @Common.TextFor
    SO_MVGR2_BEZEI_LANG              @title: '{i18n>SO_MVGR2_BEZEI_LANG}'              @sap.Label: '{i18n>SO_MVGR2_BEZEI_LANG}';
    SO_VALDT                         @title: '{i18n>SO_VALDT}'                         @sap.Label: '{i18n>SO_VALDT}'              @sap.filter.restriction: 'interval';
    SO_ABLAD                         @title: '{i18n>SO_ABLAD}'                         @sap.Label: '{i18n>SO_ABLAD}';
    SO_MFRGR                         @title: '{i18n>SO_MFRGR}'                         @sap.Label: '{i18n>SO_MFRGR}';
    SO_MFRGR_BEZEI_LANG              @title: '{i18n>SO_MFRGR_BEZEI_LANG}'              @sap.Label: '{i18n>SO_MFRGR_BEZEI_LANG}';
    TM_TNDR_TRKID                    @title: '{i18n>TM_TNDR_TRKID}'                    @sap.Label: '{i18n>TM_TNDR_TRKID}';
    SO_YRDSDV1_IMPORT_CARGO_NO       @title: '{i18n>SO_YRDSDV1_IMPORT_CARGO_NO}'       @sap.Label: '{i18n>SO_YRDSDV1_IMPORT_CARGO_NO}';
    TM_ETA_UPDATED_VISTA             @title: '{i18n>TM_ETA_UPDATED_VISTA}'             @sap.Label: '{i18n>TM_ETA_UPDATED_VISTA}';
    

};