using openOrdersSrv as service from '../../srv/order-monitoring-amoo-services.cds';
annotate service.OpenOrdersAnalytics with @(
    UI.PresentationVariant: {
            $Type         : 'UI.PresentationVariantType',
            Visualizations: ['@UI.LineItem'],
            SortOrder     : [{
                $Type     : 'Common.SortOrderType',
                Property  : SO_VBELN,
                Descending: false
            }],
            GroupBy       : [SO_VBELN]
        }
    );

annotate service.OpenOrdersAnalytics with @UI.LineItem: {
    ![@UI.Criticality]: 5,
    $value            : [
        {Value: SO_VBELN},
        {Value: SO_POSNR},
        {Value: SO_NPS},
        {Value: SO_ISSUE},
        {Value: SO_ERDAT_ITEM},
        {Value: DL_WADAT_IST},
        {Value: SO_F_ZZ0S2MATUG},
        {Value: SO_FAKSP},
        {Value: BL_VBELN_INV_LAST},
        {Value: SO_ERDAT_ORDER},
        {Value: SO_BSTKD},
        {Value: DL_VBELN},
        {Value: DL_POSNR},
        {Value: BL_POSNR_INV_LAST},
        {Value: SO_F_VBELN},
        {Value: SO_INCO1},
        {Value: SO_INCO2},
        {Value: SO_ZTERM},
        {Value: SO_F_LDDAT},
        {Value: DL_LDDAT},
        {Value: SO_MATNR},
        {Value: SO_MAKTX},
        {Value: SO_AUART},
        {Value: TM_STTRG},
        {Value: DL_WADAT},
        {Value: SO_WERKS},
        {Value: SO_ABGRU},
        {Value: SO_EDATU_REQUESTED},
        {Value: SO_WE_PARTNER},
        {Value: SO_F_VSBED},
        {Value: SO_AG_PARTNER},
        {Value: SO_F_TDDAT},
        {Value: TM_TKNUM},
        {Value: SO_VBTYP},
        {Value: SO_KWMENG},
    ]
};

annotate service.OpenOrdersAnalytics with {
    isSubtotal                      @UI:{Hidden: true};
    SO_NPS_DESCRIPTION              @UI: {Hidden: true};
     // hidden fields added just for filtering to work
    BL_POSNR_INV_LAST               @UI.Hidden;
    BL_VBELN_INV_LAST               @UI.Hidden;
    SO_FAKSP                        @UI.Hidden;
    SO_FAKSP_VTEXT                  @UI.Hidden;
    TM_STTRG                        @UI.Hidden;
    TM_STTRG_DDTEXT                 @UI.Hidden;
    SO_ABGRU                        @UI.Hidden;
    SO_ABGRU_BEZEI                  @UI.Hidden;
    SO_ISSUE                        @UI.Hidden;
    SO_ISSUE_DESCRIPTION            @UI.Hidden;
    SO_VTWEG                        @UI.Hidden;
    SO_LANDX                        @UI.Hidden;
    // SO_ORT01                        @UI.Hidden;
    SO_VKORG                        @UI.Hidden;
    SO_VKORG_NAME1                  @UI.Hidden;
    SO_CO_PARTNER                   @UI.Hidden;
    SO_CO_PARTNER_NAME              @UI.Hidden;
    SO_NY_PARTNER                   @UI.Hidden;
    SO_NY_PARTNER_NAME              @UI.Hidden;
    SO_AS_PARTNER                   @UI.Hidden;
    SO_AS_PARTNER_NAME              @UI.Hidden;
    SO_VE_PARTNER                   @UI.Hidden;
    SO_VE_PARTNER_NAME              @UI.Hidden;
    SO_AM_PARTNER                   @UI.Hidden;
    SO_AM_PARTNER_NAME              @UI.Hidden;
    SO_KNREF_HEAD                   @UI.Hidden;
    SO_VBUND                        @UI.Hidden;
    SO_EDATU_CONFIRMED              @UI.Hidden;
    SO_UNCONFIRMED_QTY              @UI.Hidden;
    SO_REQ_TEXT                     @UI.Hidden;
    SO_SUPPLY_SITUATION             @UI.Hidden;
    SO_SUPPLY_SITUATION_DESCR       @UI.Hidden;
    SO_KPEIN                        @UI.Hidden;
    SO_KMEIN                        @UI.Hidden;
    SO_HTEXT                        @UI.Hidden;
    SO_PSTYV                        @UI.Hidden;
    SO_PSTYV_VTEXT                  @UI.Hidden;
    SO_DISPO                        @UI.Hidden;
    SO_KOSCH                        @UI.Hidden;
    SO_VKBUR                        @UI.Hidden;
    SO_VKBUR_BEZEI                  @UI.Hidden;
    SO_ABSTA                        @UI.Hidden;
    SO_KNUMV                        @UI.Hidden;
    SO_SPART                        @UI.Hidden;
    SO_PRSDT                        @UI.Hidden;
    SO_ZZ0S2REVG2                   @UI.Hidden;
    SO_ZZDKPPRODB                   @UI.Hidden;
    SO_BSARK                        @UI.Hidden;
    SO_BSARK_VTEXT                  @UI.Hidden;
    SO_BASF_LOFCR                   @UI.Hidden;
    SO_GUSCON_LEVEL                 @UI.Hidden;
    SO_I_VBELN                      @UI.Hidden;
    SO_LEVEL_TYPE                   @UI.Hidden;
    SO_N_VBELN                      @UI.Hidden;
    SO_F_POSNR                      @UI.Hidden;
    SO_TRAGR                        @UI.Hidden;
    SO_TRAGR_VTEXT                  @UI.Hidden;
    SO_VKGRP                        @UI.Hidden;
    SO_VKGRP_BEZEI                  @UI.Hidden;
    SO_ROUTE                        @UI.Hidden;
    SO_F_WERKS                      @UI.Hidden;
    SO_F_VKORG                      @UI.Hidden;
    SO_F_VKORG_VTEXT                @UI.Hidden;
    SO_F_AS_PARTNER                 @UI.Hidden;
    SO_F_AS_PARTNER_NAME            @UI.Hidden;
    SO_F_LGORT                      @UI.Hidden;
    // SO_F_AUFNR                      @UI.Hidden;
    SO_F_DGLTP                      @UI.Hidden;
    SO_F_AMEIN                      @UI.Hidden;
    SO_F_PSMNG                      @UI.Hidden;
    LAST_NOTE                       @UI.Hidden;
    LAST_NOTE_FROMORDERCHAIN        @UI.Hidden;
    DL_CHARG                        @UI.Hidden;
    // DL_LFDAT                        @UI.Hidden;
    DL_HSDAT                        @UI.Hidden;
    DL_VFDAT                        @UI.Hidden;
    SO_KBETR                        @UI.Hidden;
    SO_WAERS                        @UI.Hidden;
    DL_POSAR                        @UI.Hidden;
    DL_VGBEL                        @UI.Hidden;
    DL_VGPOS                        @UI.Hidden;
    DL_LFART                        @UI.Hidden;
    DL_LFART_VTEXT                  @UI.Hidden;
    DL_TRAID                        @UI.Hidden;
    DL_ZZ0S2BLNR                    @UI.Hidden;
    DL_PEND_DEL_QUAN                @UI.Hidden;
    TM_VSART                        @UI.Hidden;
    TM_VSART_BEZEI                  @UI.Hidden;
    TM_EXTI1                        @UI.Hidden;
    TM_DPTBG                        @UI.Hidden;
    TM_DATBG                        @UI.Hidden;
    TM_DPTEN                        @UI.Hidden;
    TM_DALBG                        @UI.Hidden;
    TM_DATEN                        @UI.Hidden;
    TM_AR_DATE                      @UI.Hidden;
    TM_TDLNR_NAME1                  @UI.Hidden;
    TM_TRACKING_ID_COMP             @UI.Hidden;
    TM_TRACKING_ID_ELEM             @UI.Hidden;
    TM_SHIPMENT_ALERT               @UI.Hidden;
    // TM_SHIPMENT_CURRENT_STATUS      @UI.Hidden;
    SO_DCP_ITEM_STATUS              @UI.Hidden;
    SO_DCP_ITEM_STATUS_DESCRIPTION  @UI.Hidden;
    SO_DUE_DATE                     @UI.Hidden;
    SO_ISSUE_LOCATION               @UI.Hidden;
    SO_ISSUE_LOCATION_ITEM          @UI.Hidden;
    DL_ISSUE_ROOT                   @UI.Hidden;
    DL_ISSUE_ROOT_ITEM              @UI.Hidden;
    criticalityDueDate              @UI.Hidden;
    BL_VBELN_INV_FIRST              @UI.Hidden;
    BL_POSNR_INV_FIRST              @UI.Hidden;
    BL_FKIMG_FIRST                  @UI.Hidden;
    BL_VRKME_FIRST                  @UI.Hidden;
    BL_FKART_FIRST                  @UI.Hidden;
    BL_FKIMG_LAST                   @UI.Hidden;
    BL_FKART_LAST                   @UI.Hidden;
    BL_VRKME_LAST                   @UI.Hidden;
    BL_XBLNR                        @UI.Hidden;
    BL_NETWR_LAST                   @UI.Hidden;
    BL_ERDAT_FIRST                  @UI.Hidden;
    BL_ERDAT_LAST                   @UI.Hidden;
    BL_WAERK_LAST                   @UI.Hidden;
    SO_FOLLOWUP_NOTES_LANG          @UI.Hidden;
    SO_REASON_CODE_01_LANG          @UI.Hidden;
    SO_REASON_CODE_02_LANG          @UI.Hidden;
    SO_REASON_CODE_03_LANG          @UI.Hidden;
    SO_REASON_CODE_04_LANG          @UI.Hidden;
    SO_REASON_CODE_05_LANG          @UI.Hidden;
    SO_DEV_CONF_DATE                @UI.Hidden;
    SO_EMAIL                        @UI.Hidden;
    SO_EMAIL_SEND_DATE_F            @UI.Hidden;
    SO_EMAIL_SENT_ON                @UI.Hidden;
    SO_MDB                          @UI.Hidden;
    SO_MDB_TEXT                     @UI.Hidden;
    DL_ERDAT                        @UI.Hidden;
    SO_PERFK                        @UI.Hidden;
    SO_PERFK_LTEXT_LANG             @UI.Hidden;
    SO_F_MBDAT                      @UI.Hidden;
    DL_POSNR_BATCH                  @UI.Hidden;
    DL_LFIMG_BATCH                  @UI.Hidden;
    PO_EBELN                        @UI.Hidden;
    PO_EBELP                        @UI.Hidden;
    PO_AEDAT_HEAD                   @UI.Hidden;
    PO_AEDAT_ITEM                   @UI.Hidden;
    PO_BSART                        @UI.Hidden;
    PO_BSART_BATXT                  @UI.Hidden;
    PO_EKORG                        @UI.Hidden;
    PO_EKOTX                        @UI.Hidden;
    PO_EKGRP                        @UI.Hidden;
    PO_EKNAM                        @UI.Hidden;
    PO_EMATN                        @UI.Hidden;
    PO_WERKS_PO                     @UI.Hidden;
    PO_MENGE                        @UI.Hidden;
    PO_MEINS                        @UI.Hidden;
    PO_KUNNR                        @UI.Hidden;
    PO_KUNNR_NAME                   @UI.Hidden;
    PO_PARTNER_9A_HEAD              @UI.Hidden;
    PO_PARTNER_9O_HEAD              @UI.Hidden;
    SO_Z5_PARTNER                   @UI.Hidden;
    SO_Z5_PARTNER_NAME              @UI.Hidden;
    SO_SB_PARTNER                   @UI.Hidden;
    SO_SB_PARTNER_NAME              @UI.Hidden;
    SO_AD_PARTNER                   @UI.Hidden;
    SO_AD_PARTNER_NAME              @UI.Hidden;
    
    SO_FIRST_SO_MANDT               @UI.Hidden;
    PO_MANDT                        @UI.Hidden;
    SO_ISSUE_LOCATION_MANDT         @UI.Hidden;
    BL_MANDT_INV_FIRST_TEXT         @UI.Hidden;
    SO_FIRST_SO_MANDT_TEXT          @UI.Hidden;
    PO_MANDT_TEXT                   @UI.Hidden;
    SO_ISSUE_LOCATION_MANDT_TEXT    @UI.Hidden;
    DL_TRMTYP                       @UI.Hidden;
    DL_TRMTYP_MAKTX                 @UI.Hidden;
    DL_ZZ0S2ABGH                    @UI.Hidden;
    DL_ZZ0S2ZIEH                    @UI.Hidden;
    TM_VISTA_STATUS                 @UI.Hidden;
    TM_CURRENT_ETA_VISTA            @UI.Hidden;
    SO_BNAME                        @UI.Hidden;
    SO_IHREZ                        @UI.Hidden;
    SO_LPRIO                        @UI.Hidden;
    SO_AUGRU                        @UI.Hidden;
    SO_AUGRU_BEZEI_LANG             @UI.Hidden;
    SO_KDGRP                        @UI.Hidden;
    SO_KDGRP_KTEXT_LANG             @UI.Hidden;
    SO_WE_PARTNER_REGION            @UI.Hidden;
    SO_WE_PARTNER_REGION_BEZEI_LANG @UI.Hidden;
    SO_PRCTR                        @UI.Hidden;
    SO_TO_PARTNER                   @UI.Hidden;
    SO_TO_PARTNER_NAME              @UI.Hidden;
    TM_DPLBG_DATE                   @UI.Hidden;
    TM_ERDAT_DATE                   @UI.Hidden;
    TM_DPREG_DATE                   @UI.Hidden;
    DL_WERKS_DEL                    @UI.Hidden;
    DL_VKORG_DEL                    @UI.Hidden;
    SO_VMSTA                        @UI.Hidden;
    SO_ZZ0S2VGANN                   @UI.Hidden;
    SO_ZZ0S2LOANN                   @UI.Hidden;
    PO_REQ_DEL_DATE                 @UI.Hidden;
    PO_AB_CONF_DATE                 @UI.Hidden;
    PO_LA_CONF_DATE                 @UI.Hidden;
    PO_ZD_CONF_DATE                 @UI.Hidden;
    SO_ZZATP_CUST                   @UI.Hidden;
    SO_CONTRACT                     @UI.Hidden;
    SO_CONTRACT_ITEM                @UI.Hidden;
    SO_ZZMHDRZ                      @UI.Hidden;
    DL_SEED_COUNT                   @UI.Hidden;
    DL_SEEDS_TAGGED_GERM            @UI.Hidden;
    BL_XREF3                        @UI.Hidden;
    SO_DGSTA                        @UI.Hidden;
    SO_DGSTA_DDTEXT_LANG            @UI.Hidden;
    SO_MVGR2                        @UI.Hidden;
    SO_MVGR2_BEZEI_LANG             @UI.Hidden;
    SO_VALDT                        @UI.Hidden;
    SO_ABLAD                        @UI.Hidden;
    SO_MFRGR                        @UI.Hidden;
    SO_MFRGR_BEZEI_LANG             @UI.Hidden;
    SO_YRDSDV1_IMPORT_CARGO_NO      @UI.Hidden;
    BL_MANDT_INV_FIRST              @UI.Hidden;
    SO_MANDT                        @UI.Hidden;
    DL_MANDT                        @UI.Hidden;
    SO_FINAL_SO_MANDT               @UI.Hidden;
    SO_INCO2                        @UI.Hidden;
    SO_ZTERM                        @UI.Hidden;
    TM_MANDT                        @UI.Hidden;
    SO_F_VBELN                      @UI.Hidden;
    TM_TNDR_TRKID                   @UI.Hidden;     
    TM_OLD_ETA_VISTA_DATE           @UI.Hidden;
    TM_ETA_UPDATED_VISTA            @UI.Hidden;

};